### ISSUE TITLE
Parameters for SwannView DVR?

### ISSUE THREAD

**Issue by bassrock** [homebridge-plugins/homebridge-camera-ffmpeg#128]
Does anyone know the parameters for the SwannView dvr? The following works to create an mp4 but the default params do not work for the homebridge stream:

```
ffmpeg -re -i rtsp://***:***@192.168.2.122:554/ch04/0 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 15 testing.mp4
```

**Comment by htschmed** [comment]
I am also having a similar issue with a Samsung DVR that provides RTSP streams. I’m able to connect to the stream with ffmpeg and create an mp4 file but when running the srtp server I get the following error popping up over and over again when I add “-report” to view debug logs:

cur_dts is invalid

**Comment by htschmed** [comment]
Finally was able to get my camera streams working today and thought I would share my experience. I think the reason I was having stream failures was because the laptop I was using to host the homebridge setup was using a wireless ethernet card instead of being wired in into the network. My wifi router must have been dropping packets like crazy because as soon as i used ethernet the stream popped up in 1-2 seconds. From my reading I think it has something to do with most wifi routers will drop multicast packets because of possible ddos due to repeated propagation or something to that effect.  If your having issues with the stream be sure to hardwire your homebridge host machine to your home network first.

**Comment by bassrock** [comment]
Hmm both devices I have are hardwired so not sure that is it. There is something wrong with the stream parameters but Im not sure what needs to be changed.

**Comment by bassrock** [comment]
I can confirm that the following works for still images but I can't get the video to stream:

```
-re -i rtsp://***:***@192.168.2.122:554/ch04/0
```

**Comment by htschmed** [comment]
Is there a software firewall on the computer hosting the homebridge setup? I would try temporarily disabling the firewall and if the stream goes through adding exceptions to the firewall rules for the homebridge ports

**Comment by htschmed** [comment]
Another thing you can try is adding the ffmpeg parameter specifying to use tcp transport instead of udp.

-rtsp_transport tcp

**Comment by UserNAMEPersonThingy** [comment]
I tried this for my Swann DVR, it worked but mine might be different to yours.
`rtsp://****:****@ipaddress/Streaming/Channels/101`
To change channels change the first digit of the end number to the channel you want for example:
`Channel 1: 101`
`Channel 2: 201`
`Channel 3: 301` Etc.

**Comment by jamesgunaca** [comment]
Did anyone get this resolved? I've tried this configuration but when running homebridge, it doesn't pull in any cameras. 

"platform": "Camera-ffmpeg",
    "cameras": [
        {
            "name": "Swan Front Door",
            "videoConfig": {
                "source": "rtsp://admin:*****@192.168.1.22/Streaming/Channels/101",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "audio": true
            }
        }
    ],

**Comment by tgerring** [comment]
Bumping this old issues to add my own configuration. At first, I had tried lots of combinations of URLs, but in the end, the easiest thing was to go into the Swann NVR interface and enable RTSP, where it also listed the URLs to use.

In my case with the NVR-8550, the URL has "/ipA" to indicate the camera number and further "/B" to indicate the stream.

In my example below, the source field is encoded with a username and password (if authentication is turned on), as well as the IP:port combination. `/ip05` is for camera 5 and `/2` indicates the Mobile stream. 0 would be the main stream (4K) and 1 would be Substream (1080p).

```
[
    {
        "name": "Garage Camera",
        "videoConfig": {
            "vcodec": "h264_omx",
            "source": "-re -i rtsp://username:password@192.168.1.xxx:554/ip05/2",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 15,
            "audio": true,
            "debug": true
        }
    }
]
```
