### ISSUE TITLE
Hikvision picture stream

### ISSUE THREAD

**Issue by nathsea** [homebridge-plugins/homebridge-camera-ffmpeg#284]
Hi, i have managed to get the stream working. I am running a Hikvision NVR and capturing images from that direct. I can get the images to come up in a web page.
Just cannot get the pictures to update on the home page. The logs show that the image is being grabbed, but it doesn't update.
I have tried a number of options, i have included port 80 in my variables as well. 

-i http://admin:****@192.168.0.33/ISAPI/Streaming/channels/301/picture

http://admin:****@192.168.0.33/ISAPI/Streaming/channels/3/picture

http://admin:****@192.168.0.33/ISAPI/Streaming/channels/3/picture.jpg

Anyone able to help me out? I get a static image when i exit live view, but i assume that is just from the video?

Cheers
Nath

**Comment by scholten21** [comment]
I'm also using a Hikvision NVR and I have the opposite problem of what you are experiencing..

with me the static images updates every 10 seconds, and works fine (faster refresh would be nice)

first cam;
`"-i http://account:password@XXX.XXX.XXX.XXX:httpport/ISAPI/Streaming/channels/101/picture"`

second cam;
`"-i http://account:password@XXX.XXX.XXX.XXX:httpport/ISAPI/Streaming/channels/201/picture"`

third cam;
`"-i http://account:password@XXX.XXX.XXX.XXX:httpport/ISAPI/Streaming/channels/301/picture"`

**Comment by nathsea** [comment]
hi @scholten21 thanks for your reply. still not getting anywhere :( 
Maybe i'm expecting too much... do the static images update on your favourites / home page every 10 seconds?

**Comment by Auto-m8r** [comment]
@scholten21 @nathsea,

Theses settings work for me:


                        "source": "-re -i rtsp://XXXX:XXXXX@192.168.1.210/PSIA/Streaming/channels/1701/picture",
                        "stillImageSource": "-i http://XXXX:XXXXX@192.168.1.210/PSIA/Streaming/channels/1701/picture",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15

**Comment by scholten21** [comment]
@Auto-m8r

Do you also use a Hikvision NVR?

**Comment by scholten21** [comment]
@nathsea

Yes to your question about the refresh on the favourites page

**Comment by Auto-m8r** [comment]
@scholten21 yes i do

**Comment by frizby66** [comment]
@nathsea I had similar issues. Solution was to delete the cam feeds from homexit, delete contents of persist folder within .homebridge and then re-add the cameras in homekit. Now works a treat. If I make changes to the config.json file I have to repeat this process...looks like an issue with a mismatch between persist and updated son file!

**Comment by S474N** [comment]
Have also Hikvision NVR and my config is:

```
                {
                    "name": "K5",
                    "manufacturer": "Hikvision",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pass@IP_of_NVR:554/Streaming/Channels/502",
                        "stillImageSource": "-i http://user:pass@IP_of_NVR/ISAPI/Streaming/channels/502/picture",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 1024,
                        "maxFPS": 20
                    }
                },
```

This is for cam 5 (see on 502 on URL). For first cam you must use 102, for second 202, etc.
