### ISSUE TITLE
Manual Camera port?

### ISSUE THREAD

**Issue by dbeltman** [homebridge-plugins/homebridge-camera-ffmpeg#344]
Can i manually set a port for the camera to run on? It seems to switch ephemeral ports on every homebridge restart.

I need this for firewalling.

**Comment by kmplngj** [comment]
Any news on this?

**Comment by Edsonytic** [comment]
Can this be re-opened? I think it is still relevant.

**Comment by donavanbecker** [comment]
you can set this in config.json

```
"ports": {
        "start": 52100,
        "end": 52150
    },
```
