### ISSUE TITLE
No Motion Detected

### ISSUE THREAD

**Issue by iwanvandaele** [homebridge-plugins/homebridge-camera-ffmpeg#380]
Hi,

I have a foscam FI9961EP cam with motion detection.I've enabled the motion detection parameter but the motion is not detected in the homekit. The buttons are there but nothing happens.
Do I still need to setup something?

Regards,
Iwan Vandaele

**Comment by NorthernMan54** [comment]
Do you create an automation between your real motion sensor and the button created as part of your camera?

**Comment by NorthernMan54** [comment]
![Screen Shot 2019-10-31 at 7 24 58 PM](https://user-images.githubusercontent.com/19808920/67992692-231a9180-fc14-11e9-85bf-87f4d72c9601.png)

**Comment by iwanvandaele** [comment]
Hi,

I did that but the motion sensor is not triggered.

**Comment by jkry1214** [comment]
Same here. No motion detected but do see the boxes in live video stream for motion detection built into camera. Just does not trigger with automation. Sensor, trigger and Camera are all linked, tested as spectate tiles and no luck still. Any ideas?

**Comment by NorthernMan54** [comment]
I think there is a misunderstanding here, this feature needs a separate motion or contact sensor to work, and in the case of a camera that supports motion detection it needs a plugin that specifically supports the camera.

**Comment by WesleyLiekens** [comment]
i am not getting any motion notifications at all with an iPhone 5 and Galaxy Tab S2
So does this depend on the camera itself being capable of doing motion sensing?
Do you know what plugin I would need for this?

thanks in advance
