### ISSUE TITLE
MPEG2 settings? Maxbitrate?

### ISSUE THREAD

**Issue by uspino2** [homebridge-plugins/homebridge-camera-ffmpeg#397]
I setup a MPEG2 video stream as source. It shows in HomeKit but plays very jumpy (the computer is powerful enough). Tried reducing packet size, with slightly better results. Also, stream maxes out at 300 even when MaxBitrate is set at 3000. Any advice?

**Comment by MikeDProducer** [comment]
I have the same issue.
