### ISSUE TITLE
Utilizing Hikvision built-in motion detection

### ISSUE THREAD

**Issue by kdanaher** [homebridge-plugins/homebridge-camera-ffmpeg#436]
I have a Hikvision IP camera that is upgraded to the latest firmware (5.4.5), and it is streaming correctly using homebridge-camera-ffmpeg plugin on a Pi dedicated to running homebridge.

My question is about triggering motion snapshots: I currently have an external software (Sighthound Video) monitoring the IP cam for motion events. When it detects them, it runs a command which opens a monitored port on the pi and triggers motion via homebridge-motionsensor-web.

This is working fine and I receive snapshots in the Home app, however if possible I would like to eliminate the Sighthound software, which is running full time on an iMac, and resort fully to the built-in features of the camera.

I can see by logging into the Hikvision that it does have motion detection and that it is able to trigger "Events" and take some actions:

![image](https://user-images.githubusercontent.com/17933661/75995919-1e6c2f80-5ecb-11ea-9115-b17a659cc8a7.png)

Through some research I also see that the camera has an xml "alert stream" that can be accessed/monitored via http://[user]:[pass]@[IP]/ISAPI/Event/notification/alertStream. In theory this changes if a motion event is triggered on the camera.

So my question is. Has anyone tied this motion into homebridge via an existing plugin? Or, is there an easy method I am overlooking that's built into homebridge-camera-ffmpeg ?

Thanks!

**Comment by S474N** [comment]
+1!

BTW there is version 5.4.6

**Comment by rbswift** [comment]
I just created a feature request for this #507 Happy to merge

**Comment by rbswift** [comment]
note my current implementation is there which does work but is a pain to set up

**Comment by rbswift** [comment]
also, "line crossing" (smart events) is muuuuuch more useful than motion detection in my experience

**Comment by maisun** [comment]
Great work, very nice for my hikvision cams.
