### ISSUE TITLE
Stop "snapshot"messages being written to the log

### ISSUE THREAD

**Issue by soulcook** [homebridge-plugins/homebridge-camera-ffmpeg#447]
Is there a way to stop the Homebridge log getting clogged up with endless camera snapshot messages? "debug": false doesn't help, unfortunately.

**Comment by soulcook** [comment]
Anybody?

**Comment by AdamDempsey** [comment]
@soulcook I manually commented out [line 178](https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js#L178) in ffmpeg.js to temporarily resolved but would obvisouly need to repeat after each update.

**Comment by soulcook** [comment]
Thank you!

Could it maybe be a configuration option in future?
