### ISSUE TITLE
what need to install for Mac?

### ISSUE THREAD

**Issue by toshibochan** [homebridge-plugins/homebridge-camera-ffmpeg#450]
what I need to install for this homebridge-camera-ffmpeg work in MacOS?

**Comment by donavanbecker** [comment]
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS

**Comment by toshibochan** [comment]
I was able to install homebridge and homebridge-camera-ffmpeg and setup the config file but the camera image give me ERROR: FFmpeg exited with code 1

**Comment by donavanbecker** [comment]
Post the log

**Comment by toshibochan** [comment]
Sorry was my bad. I immigrated from raspberry and I was using h264_omx on raspberry pi and I use the same on the Mac and this was giving me error. I deleted codec line and worked okay.
Now I have to see how to do audio work on Mac.

**Comment by toshibochan** [comment]
Anyone know what I need to install on Mac OS for audio to work?

**Comment by donavanbecker** [comment]
The latest version of this plugin has ffmpeg bundled with it.

**Comment by donavanbecker** [comment]
> Anyone know what I need to install on Mac OS for audio to work? 

Which version of macOS?

**Comment by toshibochan** [comment]
@donavanbecker mojaver. I did install ffmpeg doing “brew install ffmpeg” and set audio to true in the config file but no audio. When I was using in raspberry pi audio was working.

**Comment by donavanbecker** [comment]
Can you post log and config?

**Comment by toshibochan** [comment]
How to get log?

**Comment by donavanbecker** [comment]
what are the following?

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by WesleyLiekens** [comment]
I can't seem to get it to work either on macOS. I am very new to this, so any help would be very much appreciated
------------------
[4/15/2020, 9:49:16 AM] [Camera-ffmpeg] Snapshot from iPhone at 480:270
[4/15/2020, 9:49:16 AM] [Camera-ffmpeg] An error occurs while making snapshot request
[4/15/2020, 9:49:22 AM] [Camera-ffmpeg] Start streaming video from iPhone with 1280:720@10fps (299kBit)
[4/15/2020, 9:49:22 AM] [Camera-ffmpeg] An error occurs while making stream request
[4/15/2020, 9:49:22 AM] [Camera-ffmpeg] ERROR: FFmpeg exited with code -2
------------------
Node.js Version: v12.16.2
NPM Version: v6.14.4
Homebridge Version: v0.4.53
Homebridge Camera FFmpeg Version: v0.1.17
Homebridge Config UI X Plugin Version: v4.15.1
Operating System: v10.11.6

**Comment by WesleyLiekens** [comment]
{
            "cameras": [
                {
                    "name": "iPhone",
                    "videoConfig": {
                        "source": "-i http://192.168.0.8"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }

**Comment by WesleyLiekens** [comment]
tried something new and got this

[4/15/2020, 12:58:35 PM] [Camera-ffmpeg] Start streaming video from iPhone 5 with 640:360@20fps (132kBit)
ffmpeg -i http://192.168.0.8 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 20 -f rawvideo -tune zerolatency -b:v 132k -bufsize 132k -maxrate 132k -payload_type 99 -ssrc 99161 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Bv7hq7Qqh/IHSz34XQQPDDZAsiGyjZMmXXuonaIW srtp://192.168.0.10:64897?rtcpport=64897&localrtcpport=64897&pkt_size=1316 -loglevel debug
[4/15/2020, 12:58:35 PM] [Camera-ffmpeg] An error occurs while making stream request
[4/15/2020, 12:58:35 PM] [Camera-ffmpeg] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-i',
    'http://192.168.0.8',
    '-map',
    '0:0',
    '-vcodec',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-r',
    '20',
    '-f',
    'rawvideo',
    '-tune',
    'zerolatency',
    '-b:v',
    '132k',
    '-bufsize',
    '132k',
    '-maxrate',
    '132k',
    '-payload_type',
    '99',
    '-ssrc',
    '99161',
    '-f',
    'rtp',
    '-srtp_out_suite',
    'AES_CM_128_HMAC_SHA1_80',
    '-srtp_out_params',
    'Bv7hq7Qqh/IHSz34XQQPDDZAsiGyjZMmXXuonaIW',
    'srtp://192.168.0.10:64897?rtcpport=64897&localrtcpport=64897&pkt_size=1316',
    '-loglevel',
    'debug'
  ]
}
[4/15/2020, 12:58:35 PM] [Camera-ffmpeg] ERROR: FFmpeg exited with code -2

**Comment by WesleyLiekens** [comment]
yes I do, im not sure what made the difference now but I placed ffmpeg in another location and added that in the config file and now it works

**Comment by donavanbecker** [comment]
there you go! It does look like you are running an older version of `ffmpeg` which the `ffmpeg-for-homebridge` that is a dependency of `homebridge-camera-ffmpeg` doesn't support your version of macOS.

**Comment by WesleyLiekens** [comment]
so If I install that I do not need to link to the specific path?

**Comment by donavanbecker** [comment]
no since you can't install it since you have an older macOS. it only supports 10.14 and higher which you have 10.11.

**Comment by WesleyLiekens** [comment]
but if I use another Mac or install at least 10.14.X I could install that and it should work just with camera-ffmpeg?

Sorry im new to all this and English isn't my first language

**Comment by donavanbecker** [comment]
your good. yes [ffmpeg-for-homebridge](https://github.com/homebridge/ffmpeg-for-homebridge) is a dependency of homebridge-camera-ffmpeg, so if you have 10.14 or newer it will come with ffmpeg and all you should have to do is setup the cameras.

**Comment by WesleyLiekens** [comment]
Thank you very much for the info. I am currently using this with an old iPhone 5.
You don't happen to know a good android app that would work with this plugin?
preferably one that keeps filming while using it as a touch panel on the wall

**Comment by donavanbecker** [comment]
I don’t sorry. All apple here!

**Comment by WesleyLiekens** [comment]
I noticed that when I enable audio the live feed becomes really slow.
I seem to have read that this is to do with wrong ffmpeg version.
could You point me to with version I need for this and?
And do you know which codec is recommended for iPhone 5?
Thnak you

**Comment by donavanbecker** [comment]
might need someone else to answer that.

**Comment by WesleyLiekens** [comment]
ok thank you :)
