### ISSUE TITLE
Not respecting config parameters

### ISSUE THREAD

**Issue by richie510** [homebridge-plugins/homebridge-camera-ffmpeg#452]
I have several config parameter setup with values greater than the default, but ffmpeg is being called with the default parameters. Here is my config:

                    "videoConfig": {
                        "source": "-re -i rtsp://user:pw@<ip>/live",
                        "stillImageSource": "-i rtsp://user:pw@<ip>/live",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "maxBitrate": 1200,
                        "vcodec": "copy",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": false
                    }

Here is the output I see from ps:
```
ffmpeg -re -i rtsp://user:pw@<ip>/live -map 0:0 -vcodec copy -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 2154094 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ukjECQnaBVr52tmMbojbZYhOqHdfptj8sOT+Guk+ srtp://<phone ip>:58842?rtcpport=58842&localrtcpport=58842&pkt_size=1316
```

Note: I removed private user/pw/ip

The problem i'm seeing is bad streaming quality. When debugging I'm seeing a lot of timeouts. This was working well about a month ago. 

Specifically the output from ps is showing -r 10 indicating 10 FPS when I specified 30. It also appears to be specifying 300kbit is several places when I specified 1200.

**Comment by richie510** [comment]
The new setting of minBitrate has at least helped the situation. I changed set that value to 600 and now ffmpeg is getting set with a max of 600, and that is making the stream work much better.

**Comment by malhal** [comment]
If my source stream is 1920x1080 and that same res is asked for then would it be possible to just encrypt it rather than transocde it? Do you know if the encryption will use the AES-NI in the CPU?
