### ISSUE TITLE
Unable to view feed in HK

### ISSUE THREAD

**Issue by forresthamilton** [homebridge-plugins/homebridge-camera-ffmpeg#457]
Noob here so bear with me. I am unable to view the camera feed in HK. I was able to successfully add all three cameras to HK. I was able to view the feed via VLC but now I am unable. Does ffmpeg need to be installed in a specific location? I downloaded the tar.bz2 file and extracted the contents. Do I need to install anything from it? I’ll include versions when I get back home but everything should be the most current version, I just re-installed homebridge yesterday because my Raspberry Pi died. 

Thanks
Forrest

**Comment by WesleyLiekens** [comment]
Noob here too,
I had this problem and it worked when I downloaded ffmpeg to a specific location and put the link in the config file.
I just put it in root and added
"videoProcessor": "/ffmpeg",
then everything worked fine

**Comment by forresthamilton** [comment]
I’m using homebridge config ui this time around so if I need to manually edit my config to do that, I’ll have to edit it. Mind posting that part of your config file?

**Comment by WesleyLiekens** [comment]
Keep in mind this may not work for you but it did for me

{
            "videoProcessor": "/ffmpeg",
            "cameras": [
                {
                    "name": "iPhone 5",
                    "manufacturer": "Apple",
                    "model": "iPhone 5",
                    "firmwareRevision": "10.3.4",
                    "serialNumber": "C7GKQB6XDTWD",
                    "videoConfig": {
                        "source": "-i http://192.168.0.5/live",
                        "maxStreams": 2,
                        "maxWidth": 960,
                        "maxHeight": 540,
                        "maxFPS": 20,
                        "vcodec": "h264",
                        "audio": false,
                        "motion": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

**Comment by forresthamilton** [comment]
Mine looks similar to yours for the most part. Are you using an iPhone 5 as a camera? That's interesting. 

{
            "cameras": [
                {
                    "name": "Doorbell Camera",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:password:ipaddress:8554/Video-33",
                        "maxStreams": 2,
                        "maxFPS": 30,
                        "audio": true,
                        "debug": true
                    }
                },
                {
                    "name": "Office Camera",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:password:ipaddress:8554/Video-34",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": true,
                        "motion": true
                    }
                },
                {
                    "name": "Living Room Camera",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:password:ipaddress:8554/Video-35",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": true,
                        "motion": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

**Comment by WesleyLiekens** [comment]
Yeah I had some old phones laying around and did some research and got it to work

**Comment by forresthamilton** [comment]
I might have to look into that, I have quite a few. Haha.

**Comment by WesleyLiekens** [comment]
Try to add the line
"videoProcessor": "/ffmpeg",
And specify the path to ffmpeg

**Comment by forresthamilton** [comment]
Once you extracted the contents of the tar.bz2, did you actually install anything?

**Comment by forresthamilton** [comment]
Looking at the settings for the plugin on homebridge config ui, that isn't an option. I'll have to manually add that line in. Does it matter where within the config line I place it?

**Comment by WesleyLiekens** [comment]
It’s just 1 file named ffmpeg
I placed it in root and opened it in terminal
Then when it said done I specified that path to that file

**Comment by forresthamilton** [comment]
I have mine in /home/pi/ffmpeg

**Comment by WesleyLiekens** [comment]
Then try to specify to that path

**Comment by forresthamilton** [comment]
That's what I just did, restarted homebridge and still nothing in HK

{
            "videoProcessor": "/home/pi/ffmpeg-4.2.2",
            "cameras": [

**Comment by forresthamilton** [comment]
I feel like I needed to do something after downloading and extracting the tar.bz2 file, I never ran an executable or installed anything after extracting.

**Comment by WesleyLiekens** [comment]
Have you tried deleting the cameras in HK and add them back?

**Comment by forresthamilton** [comment]
Twice.

**Comment by WesleyLiekens** [comment]
Well then I got nothing more to help you. Sorry

**Comment by forresthamilton** [comment]
No worries, I appreciate the assistance.

**Comment by forresthamilton** [comment]
Okay, so I found the issue in the config file. It changed the "@" before the IP address to a ":". I am able to view feeds from my Vivint cameras although it takes awhile to update to video, is this normal? The spinning wheel sits there for a good minute before it shows a live feed or says "Not Responding" before updating video feed.

**Comment by WesleyLiekens** [comment]
For me it has never taken longer than 5 seconds to load the live feed
