### ISSUE TITLE
Zombie ffmpeg processes running up CPU usage.

### ISSUE THREAD

**Issue by rendalltrinanes** [homebridge-plugins/homebridge-camera-ffmpeg#469]
**Describe The Bug:**
Sometimes an ffmpeg process won't terminate after exiting a live camera in homekit app causing multiple extra running processes, taking up cpu.

**To Reproduce:**
One way to reproduce is to open a live camera view and quickly exit before it loads in. Another is when you go to change the volume, sometimes notification center is engaged and it cuts off the stream and when you load back in there are now 2 processes of ffmpeg running. Exiting properly there is still a leftover process. 

**Expected behavior:**
The extra ffmpeg stream should be terminated accordingly.

**Logs:**

**Screenshots:**
Running `htop` or `ps` in the terminal reveals the many zombie streams running. I'm having this same problem with the Ring plugin. Zombie IP camera streams use over 50% of the cpu on my Synology making it so opening new streams says no connection.

**Environment:**

* **Node.js Version**: 12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.3
* **Homebridge Camera FFmpeg Version**: 0.1.17
* **Homebridge Config UI X Plugin Version**: 1.0.3
* **Operating System**: Docker

**Comment by rendalltrinanes** [comment]
Duplicate of #440

**Comment by rendalltrinanes** [comment]
#440

**Comment by rendalltrinanes** [comment]
#440 
Same issue here

**Comment by rendalltrinanes** [comment]
270% CPU usage!
<img width="447" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/55963554/81748336-91130180-945e-11ea-98d7-321865a44a82.png">

**Comment by donavanbecker** [comment]
have you tried v1.0.0?

**Comment by rendalltrinanes** [comment]
yep this is with 1.0.0
I had to kill the process manually

**Comment by BionicThomas** [comment]
Same here, thought my Pi 3b is the issue and there are not enough resources to run pi-hole on the same pi. Hence I bought a 4b now with 4GB RAM, and after setting it all up fresh I run into the same issue. This is driving the temperature up to the point that the system crashes.

**Comment by BionicThomas** [comment]
Was able to solve it for me by adding

 "vcodec": "h264_omx",

to my two Foscam cameras. 
Now they behave and no zombie processes are driving CPU and temp up.

**Comment by mrMiimo** [comment]
Same here..
I have the latest version of Homebridge (1.1.0) and Camera-ffmpeg (1.1.0) on Raspbian OS and Hikvision cam + DVR.
I tried to replicate by adding "debug = true" but after restarting homebridge it didn't happen again.
This is the sequence when it happens:
- Start streaming.
- After 10s more less the streaming shows the black screen.
- I close streaming cam to return to the homekit home.
- from the "ps -ef | grep ffmpeg" terminal show me the "orphan" process.

I will continue to try to replicate it, if I have more info I will share them with you.
