### ISSUE TITLE
Problem from outside LAN - isolated VLAN camera's network 

### ISSUE THREAD

**Issue by S474N** [homebridge-plugins/homebridge-camera-ffmpeg#473]
Hi, for my cameras I have isolated VLAN, which cannot access to internet. Cameras can access only to NTP sync and to my default LAN, where is also located Homebridge on RPi.  My main Homekit device is AppleTV and Homepod.

If I'm on my WiFi, there's no problem with pictures/streams from cameras, but outside (cellular,...) is problem. 

Can you tell me, which ports must be opened? I think, that my problem is here. But I thought, that all comunications is thought ATV or Homebridge server on RPi.

**Comment by ciavez** [comment]
same for me

**Comment by 1rado1** [comment]
Same here, different issue as I am able to access stream over cellular, but not on local wifi.

**Comment by S474N** [comment]
> Same here, different issue as I am able to access stream over cellular, but not on local wifi.

For this problem you have here 3 another issues:
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/358
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/253
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/118

This is for problem with OUTSIDE lan.

**Comment by 1rado1** [comment]
> > Same here, different issue as I am able to access stream over cellular, but not on local wifi.
> 
> For this problem you have here 2 another issues:
> #358
> #118
> 
> This is for problem with OUTSIDE lan.

Thanks, it seem as a firewall rules issue to me.
Maybe I can help you out with your issue - what is your primary router?

**Comment by S474N** [comment]
@1rado1 UniFi USG-PRO-4

**Comment by 1rado1** [comment]
> @1rado1 UniFi USG-PRO-4

I am on USG, cameras on separate VLAN, no ports forwarded.

**Comment by S474N** [comment]
@1rado1 and the settings of your VLAN? I have this VLAN isolated, without internet, only NTP allowed to internet, and RTSP/ONVIF/WEBadmin to LAN enabled. 

Do you have IPv6? I have IPv6 disabled (also on RPi with Homebridge).

**Comment by 1rado1** [comment]
> @1rado1 and the settings of your VLAN? I have this VLAN isolated, without internet, only NTP allowed to internet, and RTSP/ONVIF/WEBadmin to LAN enabled.
> 
> Do you have IPv6? I have IPv6 disabled (also on RPi with Homebridge).

VLAN have internet access, but the access to main LAN is dropped. Only route enabled is cameras —> rpi homebridge —> HomeKit hubs (atv, HomePod)

IPv6 is also disabled.

**Comment by S474N** [comment]
Can you try this command on you RPi/Homebridge device?

`netstat -an | grep 51826  `

**Comment by ciavez** [comment]
[image: image.png]
I've got 2 RPI... the one where is not working the cameras I got no result,
the one above is that one where is working... any clue?

**Comment by S474N** [comment]
@ciavez there is no image in your post ;)

**Comment by ciavez** [comment]
and now?
<img width="567" alt="image" src="https://user-images.githubusercontent.com/64363437/80921103-6c3ed000-8d74-11ea-84c7-994f23a3bb5e.png">

**Comment by S474N** [comment]
@ciavez as you can see, it uses IPv6 (tcp6).

**Comment by ciavez** [comment]
So
IPv6 is good I guess and I need to configure IPv6 as well for the second RPI
right ?

Thanks



Il giorno dom 3 mag 2020 alle 21:28 S474N <notifications@github.com> ha
scritto:

**Comment by ciavez** [comment]
![image](https://user-images.githubusercontent.com/64363437/80956128-ddc46000-8e00-11ea-9b5c-b55678999b1d.png)

sorry, my bad, see image attached.
the first one is the RPI (ciavarpibox) where the access does not work from outside LAN.
the second one is the RPI (ciavarpi) where the access does work from outside LAN.

**Comment by S474N** [comment]
I have IPv6 disabled on all devices.

**Comment by ciavez** [comment]
so, I've disabled IPv6 and I'm using
homebridge-camera-ffmpeg v0.1.19
node.js v12.16.3
NPM 6.14.5
RASPBIAN OS
Camera Foscam FI9816P
all is connected to internet through an OPENWRT router with a SIM card (behind NAT, no IP public address) 
AppleTV 4 HD

there's no way the cams (including a RPI cam) work outside the wifi.
all other various accessories work just fine!
I don't have any other option or idea on my mind.
help

**Comment by S474N** [comment]
@ciavez have same problem. On WiFi is everything OK, outside problem.

**Comment by resgroupmsr** [comment]
Have upgraded to latest plugin available for HOOBS and two cameras are also not working outside of the LAN while four others (different model) are working.

**Comment by S474N** [comment]
@resgroupmsr can you specify, which cameras you have? Manufacturer/model? Thank you!

**Comment by resgroupmsr** [comment]
> @resgroupmsr can you specify, which cameras you have? Manufacturer/model? Thank you!

Sorry thought I'd replied.  One of the ffmpeg updates fixed my issues but the camera models I have working are Amcrest IP3M-HX2W and Reolink RLC-410W
