### ISSUE TITLE
Connection failed: No route to host (in homebridge raspbian image 1.0.2)

### ISSUE THREAD

**Issue by hetkin** [homebridge-plugins/homebridge-camera-ffmpeg#487]
**Describe The Bug:**
After switching to new homeridge raspbian image, I get a No route to host error when trying to view a camera. This worked in HOOBS before I switched. I've tried connecting with the same ffmpeg command line in the terminal of the homebridge pi and i don't get the same 'no route to host' error, so i don't think it's a network issue (unless there's something weird going on in the new homebridge raspbian image)

**To Reproduce:**
Open the camera in home app

**Expected behavior:**
The camera should be visible in the home app

**Logs:**
[5/11/2020, 11:55:07] [Camera-ffmpeg] Start streaming video from Annabelle with 1280:720@30fps (299kBit)
ffmpeg -rtsp_transport tcp -re -i rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101 -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 1127052 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params D4coS57NpuMpYgawn7k2RfFiSt/VYj5fm+D88nA/ srtp://192.168.1.68:63063?rtcpport=63063&localrtcpport=63063&pkt_size=1316 -loglevel debug
ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Splitting the commandline.
Reading option '-rtsp_transport' ...
 matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option '-re' ... matched as option 're' (read input at native frame rate) with argument '1'.
Reading option '-i' ... matched as input url with argument 'rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:0'.
Reading option '-vcodec' ...
 matched as option 'vcodec' (force video codec ('copy' to copy stream)) with argument 'copy'.
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '30'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
Reading option '-tune' ...
 matched as AVOption 'tune' with argument 'zerolatency'.
Reading option '-b:v' ... matched as option 'b' (video bitrate (please use -b:v)) with argument '299k'.
Reading option '-bufsize' ...
 matched as AVOption 'bufsize' with argument '299k'.
Reading option '-maxrate' ...
 matched as AVOption 'maxrate' with argument '299k'.
Reading option '-payload_type' ...
 matched as AVOption 'payload_type' with argument '99'.
Reading option '-ssrc' ...
 matched as AVOption 'ssrc' with argument '1127052'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'rtp'.
Reading option '-srtp_out_suite' ...
 matched as AVOption 'srtp_out_suite' with argument 'AES_CM_128_HMAC_SHA1_80'.
Reading option '-srtp_out_params' ...
 matched as AVOption 'srtp_out_params' with argument 'D4coS57NpuMpYgawn7k2RfFiSt/VYj5fm+D88nA/'.
Reading option 'srtp://192.168.1.68:63063?rtcpport=63063&localrtcpport=63063&pkt_size=1316' ... matched as output url.
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.

Finished splitting the commandline.
Parsing a group of options: global .
Applying option loglevel (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101.
Applying option re (read input at native frame rate) with argument 1.
Successfully parsed a group of options.
Opening an input file: rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101.

[tcp @ 0x2acc690] No default whitelist set
[tcp @ 0x2acc690] Original list of addresses:

[tcp @ 0x2acc690] Address 192.168.1.36 port 8554
[tcp @ 0x2acc690] Interleaved list of addresses:
[tcp @ 0x2acc690] Address 192.168.1.36 port 8554
[tcp @ 0x2acc690] Starting connection attempt to 192.168.1.36 port 8554

[tcp @ 0x2acc690] Connection attempt to 192.168.1.36 port 8554 failed: No route to host

[tcp @ 0x2acc690] Connection to tcp://192.168.1.36:8554?timeout=0 failed: No route to host
rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101: No route to host

[5/11/2020, 11:55:07] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

**Output of manual ffmpeg run within homebridge terminal**

pi@homebridge:/var/lib/homebridge $ ffmpeg -rtsp_transport tcp -re -i rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[h264 @ 0x3d49730] number of reference frames (1+2) exceeds max (2; probably corrupt input), discarding one
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101':
  Metadata:
    title           : pps_rtsp
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 12 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
At least one output file must be specified
pi@homebridge:/var/lib/homebridge $ 

**Homebridge Config:**

 "cameras": [
                {
                    "name": "Annabelle",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:1@192.168.1.36:8554/Streaming/Channels/101",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "maxBitrate": 600,
                        "vcodec": "copy",
                        "packetSize": 1316,
                        "debug": true,
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: v6.14.4
* **Homebridge Version**: v1.0.4
* **Homebridge Camera FFmpeg Version**: v0.1.19
* **Homebridge Config UI X Plugin Version**: v4.18.0
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by robertmehrer** [comment]
ifconfig and check your gateway on the server... it doesnt know where that network is... probably bad DHCP or you assigned the IP wrong on the server.
