### ISSUE TITLE
Two-Way Audio

### ISSUE THREAD

**Issue by llemtt** [homebridge-plugins/homebridge-camera-ffmpeg#489]
Two way audio works with camera-ffmpeg.

_Originally posted by @normen in https://github.com/KhaosT/homebridge-camera-ffmpeg/pull/488#issuecomment-627162169_

Very good news, how do we configure?

**Comment by normen** [comment]
Copy of https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/174

**Comment by llemtt** [comment]
Ok but do you, or someone else, have ever merged the code into this repository?

**Comment by normen** [comment]
Right, it was never preared as a proper PR, only random forks with bits of code, like sadly many of the camera-ffmpeg derivates. Some even try to make money off of their bad forks by sticking their paypal badge on them.

**Comment by california444** [comment]
+1

**Comment by california444** [comment]
Would it be possible / a good idea to support ONVIF standard for 2 way audio?
An additional header (Require backchannel) must be send:
[Require back channel info](http://www.happytimesoft.com/knowledge/audio-back-channel.html)

**Comment by normen** [comment]
ONVIF only really allows you to find the cameras streams and to control some things like pan/tilt if thats available. It's not really a standard on how to send and receive audio or video data or what codecs to use.

So it might help a bit but really is probably just a whole new can of worms. I did play around with it to get pan/tilt working in this plugin but didn't get very far.

**Comment by llemtt** [comment]
ffmpeg doesn't support the rtsp backchannel so ONVIF can't be supported by ffmpeg based plugins
