### ISSUE TITLE
Just some praise and kudos for the new v1.0.0.

### ISSUE THREAD

**Issue by houser42** [homebridge-plugins/homebridge-camera-ffmpeg#490]
Just wanted to say a quick thanks for the new v1.0.0.
It works really well and now with audio also for my rtsp streams.
really great, thank you!!

**Comment by NorthernMan54** [comment]
@oznu gets the big congrats on this, with the packaging of ffmpeg with the plugin, the number of weird issues should drop off now.

**Comment by houser42** [comment]
Alright, congrats to great work @oznu !
It also starts very quickly in homekit now. Yes, it rocks!
