### ISSUE TITLE
Allow HTTP request to trigger dummy motion sensor

### ISSUE THREAD

**Issue by njakobsen** [homebridge-plugins/homebridge-camera-ffmpeg#491]
Instead of using the dummy button to trigger the motion detector via a HomeKit automation, I would like to trigger it via an HTTP request. This would allow me to use my Synology Surveillance Station to notify homebridge-camera-ffmpeg, which would in turn trigger its dummy motion Sensor, avoiding the need for any HomeKit configuration, while still being able to create motion notifications with a screenshot.

The HTTP request would include a param that identifies which device detected motion, e.g. `device=backyard`, which would correspond to a property in the configuration JSON on each camera entry.

**Comment by joffreyha** [comment]
@njakobsen you can use this plugin for your use-case: https://github.com/aficustree/homebridge-sss-platform

**Comment by njakobsen** [comment]
I do use that plugin to create a motion sensor in homekit, but since iOS 13 that sensor must be part of a camera to generate a thumbnail in the notification. To solve this, @KhaosT has created the `motion` option in this project, however, that requires you to connect your homebridge-sss-platform motion sensor in the Home app to the dummy switch generated by the `motion` option.

Instead, I'd like to forego the homebridge-sss-platform motion sensor completely and trigger the dummy motion sensor generated by the `motion` option in this project. I would tell the Surveillance Station to trigger the dummy motion sensor in this project instead of the one in homebridge-sss-platform. That way we wouldn't need to use the Home app to create an automation to connect the homebridge-sss-platform motion sensor to the dummy motion sensor in the camera accessory.

I hope that makes my request a bit clearer.

**Comment by phralh** [comment]
I would also like to see support for triggering motion via HTTP and/or MQTT. Perhaps with an config option to not generate a dummy switch at all as it would not be needed. I'd like to avoid  dummy switches filling my home app that's already 150+ accessories and increasing.

Regards
Fredrik

**Comment by njakobsen** [comment]
@phralh yes, this implementation would eliminate the need for the dummy switch too.

**Comment by normen** [comment]
Just do a clean, unobtrusive implementation, best without pulling in additional dependencies - Node has built-in support for http anyway. Afaict this project is (now) heavily dependent on contributions and PRs are reviewed and added quickly.

**Comment by Edsonytic** [comment]
Adding my support for this request
