### ISSUE TITLE
Cannot add cameras in apple homekit

### ISSUE THREAD

**Issue by tobihoby** [homebridge-plugins/homebridge-camera-ffmpeg#493]
**Describe The Bug:**
after updating the plugin to version 1.0.0 my 4 cameras were still recognized in the homekit, but could no longer call up any data. I removed the cameras in the homekit, uninstalled and reinstalled the plugin, added only one camera to the test (see below). The json is error-free, no errors in the log, the plugin is loaded correctly according to the log, but the camera is not recognized in the homekit and cannot be found and added via camera accessories.

**To Reproduce:**
the error is permanent

**Expected behavior:**
the camera is recognized in the home kit as a new camera and can be added as a camera accessories

**Logs:**
no error in the log

**Homebridge Config:**

[
    {
        "name": "CamEingang",
        "debug": true,
        "videoConfig": {
            "source": "-re -i rtsp://admin:password@192.168.0.19:554/Streaming/Channels/101",
            "stillImageSource": "-i http://admin:password@192.168.0.19:82/streaming/channels/101/picture?"
        }
    }
]

this config worked without problems before the update

**Environment:**

* **Node.js Version**:12.13.1
* **NPM Version**:Hoobs 3.2.3
* **Homebridge Camera FFmpeg Version**:1.0.0

**Comment by normen** [comment]
Try adding this right before the "cameras" entry:
`"videoProcessor": "/usr/bin/ffmpeg",`

**Comment by tobihoby** [comment]
The entry was set, moved it in front of the camera entry, now I have the following entry in the log:
CamEingang is running on port 43385

But unfortunately the camera still doesn't show up in the homekit to add it


{
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg",
                "videoProcessor": "/usr/bin/ffmpeg"
            },
            "cameras": [
                {
                    "name": "CamEingang",
                    "debug": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:password@192.168.0.19:554/Streaming/Channels/101",
                        "stillImageSource": "-i http://admin:password@192.168.0.19:82/streaming/channels/101/picture?"
                    }
                }

**Comment by normen** [comment]
Maybe try renaming the cameras, then they should be "new" for HomeKit.

**Comment by tobihoby** [comment]
oh my god, that's it, thank you very much!
