### ISSUE TITLE
Foscam Camera FI9853EP V2 Randomly Does Not Stream

### ISSUE THREAD

**Issue by micleeso** [homebridge-plugins/homebridge-camera-ffmpeg#494]
I have five Foscams two of which have persistent but random stream failures (FI9853EP V2).  At times both work, or randomly one or the other fails.

The IOS device receives " No Response - The camera is not responding". These are labelled as Back Camera East and Back Camera West.
 
I have three other cameras that work without issue ( FI9853EP version 1). These are labelled as Front Camera West, Front Camera East, and PT Camera.

All cameras are using the same configuration methods as seen in my config. I can not find the root cause or see an issue in the log.

**Logs:**
See attached files Foscam working, Foscam not working txt files

Config of FFMPEG see attached file name FFmpeg config txt.

**Environment:**

* **Node.js Version**: 12.14.1
* **NPM Version**: 6.14.5
* **Homebridge Version**: 3.2.3
* **Homebridge Camera FFmpeg Version**: N-96863-g9b22254331
* **Homebridge Config UI X Plugin Version**: 1.1.0

* **Operating System**:  Raspbian

[foscam working.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4625220/foscam.working.txt)
[foscam not working.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4625221/foscam.not.working.txt)
[ffmpeg config.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4625222/ffmpeg.config.txt)

**Comment by NorthernMan54** [comment]
Looking at your config, they are different on the ones that are not working.  Have you tried normalizing the config

**Comment by micleeso** [comment]
Updated Config and Updates Applied.

Earlier today the troubled cameras worked. At this moment nope.

(is there a way to configure the log greater than 500 entries?)

* **Node.js Version**: 12.14.1
* **NPM Version**: 6.14.5
* **Homebridge Version**: 3.2.4
* **Homebridge Camera FFmpeg Version**: N-96863-g9b22254331
* **Homebridge Config UI X Plugin Version**: 1.1.1
* **Operating System**: Raspbian

[ffmpeg-consistent.txt](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/files/4631013/ffmpeg-consistent.txt)

**Comment by NorthernMan54** [comment]
Looking at your two configs - Working

```
    {
        "name": "Front Camera West",
        "videoConfig": {
            "source": "-rtsp_transport tcp -re -i rtsp://username:password@xxx.xxx.xxx.xxx:9982/videoMain",
            "stillImageSource": "-i http://xxx.xxx.xxx.xxx:9982/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=username&pwd=password&",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "vcodec": "copy",
            "audio": false,
            "debug": false
        }
    },
```

Not Working

```
    {
        "name": "Front Camera West",
        "videoConfig": {
            "source": "-rtsp_transport tcp -i rtsp://username:password@xxx.xxx.xxx.xxx:9982/videoMain",
            "stillImageSource": "-i http://xxx.xxx.xxx.xxx:9982/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=X&pwd=X&",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 30,
            "maxBitrate": 300,
            "mapvideo": "0:0",
            "vcodec": "copy",
            "audio": false,
            "debug": false
        }
    },
```

These appear to be the problematic settings

```
            "maxBitrate": 300,
            "mapvideo": "0:0",
```

When it was working you didn't have these

**Comment by micleeso** [comment]
The front cameras are not an problem.
The back cameras have issues.
Those parameters bitrate and mapvideo don’t change the outcome. they’re defaults too. 
I tried all types of configurations.

**Comment by cwittenberg** [comment]
I have the exact same issue as you. @micleeso 
I have two FI9853EP connected to Homebridge.
When in Home app on iPhone: 'The camera is not responding' - only on certain occasions it appears to work.
