### ISSUE TITLE
Do not receive doorbell notification video

### ISSUE THREAD

**Issue by sergoo-lbt** [homebridge-plugins/homebridge-camera-ffmpeg#495]
When I click on the doorbell button, only a notification about the call comes in but the video does not turn on. If you turn on just a virtual trigger in the camera, then everything works.

**Comment by normen** [comment]
What do you mean by "a virtual trigger in the camera"? When you press (or automate) the trigger button you usually get a notification on your phone with a (still) image of the camera, you can click on it (or pull it down on iOS/iPadOS) to see a live video and buttons to open any doors in the same room. On iWatch you get the same - an image and when you tap on it you get a live video.

**Comment by sergoo-lbt** [comment]
Right! But in this case, you get a notification without an image.

**Comment by normen** [comment]
Yes you do, at least if everything is working normally. Do you get still images at all with your cameras? Maybe the still image URL is just set wrong.

**Comment by sergoo-lbt** [comment]
> Yes you do, at least if everything is working normally. Do you get still images at all with your cameras? Maybe the still image URL is just set wrong.

Deleted the camera. Added the camera again. Now everything is working. Notification with an image and when you press it, the ether opens.
