### ISSUE TITLE
Is camera stream encrypted?

### ISSUE THREAD

**Issue by cowboydaks** [homebridge-plugins/homebridge-camera-ffmpeg#499]
Forgive me if this is readily apparent, but are the camera streams I set up through this plugin transmitted/accessed by this plugin in an encrypted (end-to-end encrypted) format?  Or are the username/passwords of cameras transmitted in the clear in a way that is interceptable by anyone on my home network, or outside my home network?  I just don't want my home security cameras broadcasting out to the world, readily accessible, or easily accessible to someone wifi sniffing out on the street.

I really appreciate your answering of these questions!

Node.js Version: 12.16.3

NPM Version: 6.14.4

Homebridge Version:1.04

Homebridge Camera FFmpeg Version: 1.1.1

Homebridge Config UI X Plugin Version: 4.19.0

Operating System: MacOS

**Comment by normen** [comment]
It depends on your camera, it's the same as getting a stream via VLC or another video player. As for HomeKit itself, when the stream leaves your home network (e.g. via an AppleTV or HomePod) it's transported using Apples HomeKit encryption.

Actual end-to-end encryption of the video stream (if you really know what that means) is something that very few video streaming apps actually do, usually its enough to protect access to the stream. So any "bad hosts" on the way between you and your destination could decode your video. So whatever you have to hide, don't try to hide it on the internet, thats a bad idea in general.

**Comment by cowboydaks** [comment]
Thank you for the info-I just don't want my home security cameras broadcasting out to the world, readily accessible, or easily accessible to someone wifi sniffing out on the street.

**Comment by normen** [comment]
If your WiFi is safe then your cameras are relatively safe too. The NSA will still get in though.
