### ISSUE TITLE
video codec: copy

### ISSUE THREAD

**Issue by kontur11** [homebridge-plugins/homebridge-camera-ffmpeg#500]
When using video codec: copy, streaming video is enabled 1 time out of 5-7 attempts. The same situation if the camera is thrown from surveillance station synology. In the log says Failed to parse interval and specification ". With the H264 stream, everything works fine. 
Homebridge 1.0.4
 docker synology,
 camera ffmpeg 1.1.0. 
C what parameters can affect this?

**Comment by normen** [comment]
Really only the stream settings in your cam can alleviate this. I only have 2 different types of cameras that do work with "copy" even though technically the others are H264 main profile too. "copy" really is very much dependent on what your cam puts out, as the name suggests.

**Comment by kontur11** [comment]
Lowering the bitrate to 300 in camera settings really helped, thank you.
