### ISSUE TITLE
How to Activate Doorbell Trigger

### ISSUE THREAD

**Issue by JDogg016** [homebridge-plugins/homebridge-camera-ffmpeg#502]
So the addition of a doorbell trigger is really neat.... now the question becomes how to actually trigger the switch when the doorbell is pressed.  I have an August Doorbell, and my first thought was IFTT to a web hook but then I thought perhaps I am overcomplicating things.

Anyone have any ideas?

**Comment by NorthernMan54** [comment]
To trigger mine, I'm using a Home App automation.

**Comment by JDogg016** [comment]
Do you have a device that triggers the switch to turn on?

**Comment by normen** [comment]
You can use any other switch in Homekit. I personally use a cheap 433MHz receiver that picks up the signal of my standard doorbell button and makes that a switch in HomeKit. Then I automated the bell switch to trigger when that 433 doorbell button is pressed. Voila, I see the postman :)
