### ISSUE TITLE
Audio is noisy/buggy plus how to combine external aac audio with video

### ISSUE THREAD

**Issue by Vannixxo** [homebridge-plugins/homebridge-camera-ffmpeg#505]
Hello! Really nice update.. everything seems to work, but the audio I get from my stream is full of artifacts and noisy/stuttered, the rtsp with VLC is perfect, what setting should I try to improve it?

Another question is: I've got another RTSP camera that has separated h264 stream and aac stream, I tried playing with -map settings but no luck, is it possible to specify a second audio stream to be combined?
"source": "-i rtsp://192.168.1.206:554/ch0_0.h264 -i rtsp://192.168.1.206/ch0_2.aac",

Thanks for the help!

**Comment by kurtwarwick-new** [comment]
Hi

I am having the same issue. VLC audio is perfect, however, the audio through Homebridge is as described above.

Thanks!

**Comment by Vannixxo** [comment]
> Hi
> 
> I am having the same issue. VLC audio is perfect, however, the audio through Homebridge is as described above.
> 
> Thanks!

Hi, I seem to have solved specifying a smaller packet size in the ffmpeg settings, now it glitches sometimes but for the most part the audio is clear... Waiting to understand if there is a way as I already asked to combine VIDEO and AUDIO from two separate stream URLs
