### ISSUE TITLE
Add Motion Detection / Line Crossing Detection for Hikvision

### ISSUE THREAD

**Issue by rbswift** [homebridge-plugins/homebridge-camera-ffmpeg#507]
**Is your feature request related to a problem? Please describe:**
Hikvision Cameras have a HTTP CGI interface that streams human readable information from the camera. This includes Motion Detection and Line Crossing Events. Getting these into Homebridge and this plugin is currently quite difficult.

**Describe the solution you'd like:**
The plugin should make a long-lived http connection to _/ISAPI/Event/notification/alertStream_ on the camera and string pattern match for a configurable string (default "linedetection") then trigger the plugin's motion detection accessory.

**Describe alternatives you've considered:**
Currently using [hikvision-to-mqtt](https://github.com/zoilomora/hikvision-to-mqtt) and [mqttthing](https://github.com/arachnetech/homebridge-mqttthing) but it's very circuitous and requires some customisation.

**Additional context:**
This would be a much cleaner way for supported cameras than the current motion detection workaround.

**Comment by maisun** [comment]
It’s a neat feature, hope it can be merged

**Comment by rbswift** [comment]
no appetite for this? or just no developers
