### ISSUE TITLE
Unable to get still jpg image in Home app - ESP32 Cam running RTSP

### ISSUE THREAD

**Issue by tommakesmusic** [homebridge-plugins/homebridge-camera-ffmpeg#514]
**Describe Your Problem:**
 Hi all. This isn't the biggest problem ever but I'd definitely like to see if it can be sorted! 

After many days trying to get home bridge-camera-ffmpeg to recognise a http stream from an ESP32 Cam, (despite using the config given in the tested configs part of the git - this always resulted in "ERROR: FFmpeg exited with code 1")  I found this instructable on how to get the ESP Cam to stream via RTSP: https://www.instructables.com/id/9-RTSP-Video-Streamer-Using-the-ESP32-CAM-Board/

This is going to be a homemade doorbell camera and is working like a charm except for one slight issue - I cannot get the plugin to capture a snapshot / still image jpeg. If i go to the url in the config with a browser it serves up a jpeg. I cannot get camera-ffmpeg to grab that image and send it to Home.

The app does, however, show the last frame captured from the video stream as the thumbnail.

The camera does display an image if you go to 192.168.1.XXX/jpg  (with the filename "capture" - see screenshots and code snippet below) but I don't know enough about camera-ffmpeg to get this still image served to apple Home. I've included a successful entry from an ieGeek commercial rtsp camera as an example of what I expect the ESP32 Cam would show if successful.

Clearly I'm doing something wrong and am a bit out of my depth but if anyone could suggest a way forward I am all ears/eyes! Also, if anyone has any suggestions to improve the config etc. please let me know.

**Logs:** -- _Italics added by me as comment_
23/05/2020, 14:01:46 [Churchview] Snapshot from Garden at 480:270
23/05/2020, 14:01:46 ffmpeg -i http://USER:PASSWORD@192.168.1.190/tmpfs/auto.jpg -t 1 -vf scale=480:270 -f image2 - _(IMAGE SERVED TO HOME APP)_
// (some stuff removed)23/05/2020, 14:02:18 [Churchview] Snapshot from DoorbellCam at 480:270
23/05/2020, 14:02:20 [Churchview] Start streaming video from DoorbellCam with 640:360@5fps (132kBit)
23/05/2020, 14:02:42 [Churchview] Stopped streaming
23/05/2020, 14:02:51 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:03:01 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:03:21 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:03:51 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:04:31 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:05:21 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:06:21 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:07:31 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:08:51 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:10:21 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:12:02 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_
23/05/2020, 14:13:42 [Churchview] Snapshot from DoorbellCam at 480:270 _NO IMAGE IN APP_

**Homebridge Config:**

{
        "name": "DoorbellCam",
        "videoConfig": {
            "name": "ESP32-Cam",
            "manufacturer": "espressif",
            "model": "ESP32-Cam",
            "serialNumber": "01-23-45-67",
            "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.172:8554/mjpeg/1",
            "stillImageSource": "-i http://198.162.1.172/jpg/capture.jpg",
            "maxStreams": 2,
            "maxWidth": 800,
            "maxHeight": 600,
            "maxFPS": 5
        }
    }

**Relevant code from the Arduino IDE:**
//some stuff 
void handle_jpg(void)
{
    WiFiClient client = server.client();

    cam.run();
    if (!client.connected())
    {
        return;
    }
    String response = "HTTP/1.1 200 OK\r\n";
    response += "Content-disposition: inline; filename=capture.jpg\r\n";
    response += "Content-type: image/jpeg\r\n\r\n";
    server.sendContent(response);
    client.write((char *)cam.getfb(), cam.getSize());
}
//some more stuff

Here are a couple of screenshots of the static image in a browser and showing the filename...

![Screenshot 2020-05-23 at 14 30 50](https://user-images.githubusercontent.com/22780456/82732158-61d47e00-9d03-11ea-86e0-dfe9e41d824b.png)
![Screenshot 2020-05-23 at 14 31 04](https://user-images.githubusercontent.com/22780456/82732160-65680500-9d03-11ea-94dd-8a0614d90706.png)

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 3.2.6
* **Homebridge Camera FFmpeg Version**: 1.1.1
* **Homebridge Config UI X Plugin Version**: ???
* **Operating System**: Hoobs Raspian / Raspberry Pi 3

**Comment by Fienberber** [comment]
I don't know if you found your problem but try removing `"stillImageSource": "-i http://198.162.1.172/jpg/capture.jpg",`
Since this is optional, the plugin is going to take a frame of the rstp stream. I've done that in your exact setup and it works.
