### ISSUE TITLE
Description for motion parameter missing from wiki

### ISSUE THREAD

**Issue by usmcguy** [homebridge-plugins/homebridge-camera-ffmpeg#516]
on main page of project...

> **motion** enable a dummy switch and motion sensor to trigger picture notifications in iOS 13, defaults to false. See wiki for more detailed instructions.

However, Wiki page has no mention of how to use the motion parameter

**Comment by oznu** [comment]
Anyone with a GitHub account can edit the wiki.

**Comment by NorthernMan54** [comment]
https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications
