### ISSUE TITLE
client_secret.json      

### ISSUE THREAD

**Issue by JimmyEyeball** [homebridge-plugins/homebridge-camera-ffmpeg#521]
![snippp](https://user-images.githubusercontent.com/50030249/83126687-176f4a80-a0d1-11ea-8ff9-0b836ab8ed60.PNG)
error loading client secret file, please follow the instructions in the readme!!!error: enoent: no such file or directory, open 'undefined/.homebridge/client_secret.json'

I GIVE UP!!!!! Hours please just tell me where I should be putting this on a Pi HB Hours..... I assume I have it in the wrong place but I cant work out where it should be... PLESEEE HELP....

/root/.homebridge

/var/homebridge

I can keep going....

So my config.json lives @ /var/hbPeople so clearly this is where it should go but I'm still getting the error so should this be somewhere different on RPi or is it possible to point to it in the config somehow?

Everything is working fine I have the cameras in HomeKit and am getting Doorbell notifications I thought that should be the hard part lol So if I could just get the Pics up to Google Drive it would be perfect....

Can these pics even be stored locally? 

**Logs:**
May 28 02:24:42 raspberrypi homebridge[6740]: Error loading client secret file, please follow the instructions in the README!!!Error: ENOENT: no such file or directory, open 'undefined/.homebridge/client_secret.json'

**Homebridge Config:**
{
					"name": "Front Door",
					"doorbell": true,
					"uploader": true,
					"vcodec":"h264_omx",
					"videoConfig": {
						"source": "-re -i rtsp://192.168.0.28:554/user=admin&password=xxxxxx&channel=1&stream=0.sdp?",
						"maxStreams": 1,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 3
					}
				},
				{
					"name": "Back Door",
					"doorbell": true,
					"uploader": true,
					"vcodec":"h264_omx",
					"videoConfig": {
						"source": "-re -i rtsp://192.168.0.28:554/user=admin&password=xxxxxx&channel=2&stream=0.sdp?",
						"maxStreams": 1,
                                                "maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 3
					}
				}

**Environment:**

* **Node.js Version**: v12.14.1
* **NPM Version**: v6.14.4
* **Homebridge Version**: Version 1.1.0
* **Homebridge Camera FFmpeg Version**: v1.2.0
* **Homebridge Config UI X Plugin Version**: v4.21.0
* **Operating System**:  Raspbian

**Comment by NorthernMan54** [comment]
Jimmy,

The code for this looks like this

var TOKEN_DIR = (process.env.HOME || process.env.HOMEPATH ||
process.env.USERPROFILE) + '/.homebridge/‘;

And it is looking for an environment variable called HOME or HOMEPATH or USERPROFILE

Does your runtime environment set any of those typical shell variables?

Bash on Raspbian and OS X automatically set HOME

Sean

**Comment by JimmyEyeball** [comment]
which I'm assuming this is the /root/ the default Homebridge directory would usually be /root/.homebridge but as I have a few instances running this particular instance running the homebridge-camera-ffmpeg plugin is located @ /var/hbPeople/ this is the location of the config.json so that should be where it should go and obviously the first place I put it. But just in case.... 

Ive also dropped it at.

/root/
/root/.homebridge/
/.homebridge/
/var/
/var/homebridge/
/var/hbPeople/
/usr/local/lib/node_modules/homebridge-camera-ffmpeg/
/etc/default/homebridge
/etc/systemd/system/

**Comment by JimmyEyeball** [comment]
Did I do something wrong in the previous steps that it doesn't recognise the file?

I picked desktop app for the API...
