### ISSUE TITLE
Switch used to trigger Motion Detection Snapshots (Rich Notifications) doesn't reset automatically.

### ISSUE THREAD

**Issue by teymur1988** [homebridge-plugins/homebridge-camera-ffmpeg#522]
**Describe The Bug:**

Hi @normen  So, I noticed this since we had the doorbell function added to this plugin. When doorbell function is enabled for any of the cameras in the config, the switch used to trigger snapshots (rich notifications), doesn't reset automatically. In the logs tho it says resetting switch to false, but the switch state doesn't actually change, it stays on.
**To Reproduce:**

Just have doorbell flag enabled for one of the cameras and turn the snapshot switch on, it will stay on.
**Expected behavior:**

Expected behavior, is that the switch should reset automatically after being turned on. If the doorbell flag isn't enabled the switch works as expected.
**Logs:**

```
[5/28/2020, 17:59:20] [Camera-ffmpeg] Setting Entrance Camera Motion to true
[5/28/2020, 17:59:20] [Camera-ffmpeg] Setting Entrance Camera Motion to false
```

**Homebridge Config:**

```json
                {
                    "name": "Entrance Camera",
                    "uploader": true,
                    "motion": true,
                    "doorbell": true,
                    "videoConfig": {
                        "source": "-rtsp_transport udp -i rtsp://login:password@ip:port/udp/av0_0",
                        "stillImageSource": "-i http://ip/img/snapshot.cgi?user=user&pwd=pwd&res=0",
                        "maxFPS": 25,
                        "vcodec": "copy",
                        "audio": true,
                        "debug": false
                    }
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
12.16.2
* **NPM Version**: 
6.14.4
* **Homebridge Version**: 
1.1.0
* **Homebridge Camera FFmpeg Version**: 1.2.0
* **Homebridge Config UI X Plugin Version**: 4.21.0
* **Operating System**:  Raspbian

**Comment by normen** [comment]
So you're saying that when you enable the doorbell function the switch
for the _motion_ notification doesn't reset anymore? The doorbell switch
does reset though?

**Comment by normen** [comment]
Okay, I see the issue, the old motion code just grabs the first switch
it can get hold of and resets that, resulting in it grabbing the switch
of the doorbell function.. I don't know why that code is in a named
global function anyway, I guess it should be done like the doorbell code
so that it always references its own switch?

**Comment by teymur1988** [comment]
> So you're saying that when you enable the doorbell function the switch for the _motion_ notification doesn't reset anymore? The doorbell switch does reset though?

Yeah absolutely. The doorbell switch does reset alright! No problem with that so far.





> Okay, I see the issue, the old motion code just grabs the first switch it can get hold of and resets that, resulting in it grabbing the switch of the doorbell function.. I don't know why that code is in a named global function anyway, I guess it should be done like the doorbell code so that it always references its own switch?

If you think, that's what's happening, then it must be it. Thanks for looking at i tho.

**Comment by normen** [comment]
I opened a PR under #523 fixing the issue - let's see if and when they add it.

**Comment by donavanbecker** [comment]
> I opened a PR under #523 fixing the issue - let's see if and when they add it.

@normen @teymur1988 this is in 1.2.1!

**Comment by normen** [comment]
🚀 boom

**Comment by NorthernMan54** [comment]
I thought we could have also updated the names for the “fake” motion sensor and switch to indicate that the switch is the trigger and motion is a dummy by appending to the camera name similar to the doorbell.

**Comment by donavanbecker** [comment]
> I thought we could have also updated the names for the “fake” motion sensor and switch to indicate that the switch is the trigger and motion is a dummy by appending to the camera name similar to the doorbell.
@normen thoughts?

**Comment by normen** [comment]
Right but I wasn't sure if that wouldn't mess up peoples automations as
I suppose most use this with an automation.

**Comment by NorthernMan54** [comment]
Give me an hour or so, and I will test.

**Comment by normen** [comment]
The switch doesn't get a specific UUID, pretty sure it'll be a "new" switch in
HomeKit as the UUID will be derived from the name afaik. But empirical
data would certainly help 😄

**Comment by NorthernMan54** [comment]
Confirmed, changing the name breaks existing automations.  I did have a switch here

![IMG_4949](https://user-images.githubusercontent.com/19808920/83178321-5fe93100-a0ee-11ea-9145-1e610a9cbf6a.PNG)

**Comment by teymur1988** [comment]
Hello there, @normen  @NorthernMan54  This kept going on since 2.0.0, the motion switch doesn't auto-reset for one of my camera's and it's ok for another one.

Regards

Teymur
