### ISSUE TITLE
Adding delay

### ISSUE THREAD

**Issue by alexndrs** [homebridge-plugins/homebridge-camera-ffmpeg#526]
Is it possible to add delay to stream? I would like to have a two second delay on HomeKit.

**Comment by NorthernMan54** [comment]
Snapshot or video stream?

**Comment by alexndrs** [comment]
Video stream.

**Comment by NorthernMan54** [comment]
I’m not sure if we would make this type enhancement

But I have to ask, why?  What is your use case?


Most people ask to have the video stream quicker?

**Comment by alexndrs** [comment]
Okay, so my motion detection software sends a command that activates a dummy switch in HomeKit then takes the photo. But this process takes around 2 second. And when the picture then is take the motion is out of picture. So if I set a delay it will capture the right moment. Do you understand?

**Comment by NorthernMan54** [comment]
What your asking for is the plugin to go back in time and take a snapshot 2 seconds before the motion sensor is triggered.

**Comment by alexndrs** [comment]
Oh, I didn’t know there was a plugin like that. What is it called?

**Comment by alexndrs** [comment]
Otherwise my motion software outputs an image when motion is detected. Is there any way to make motion detection display an image from path?

**Comment by NorthernMan54** [comment]
Are you asking to have the snapshot request read a file instead of the camera.   You should be able to achieve this by changing the settings for stillImageSource and have it point to a file instead

**Comment by alexndrs** [comment]
I might go for the plugin you was talking about. Snapshot back in time 2 seconds. Where can I find more about that?

**Comment by NorthernMan54** [comment]
There is no plugin that has the capability to go back in time and take a snapshot.

**Comment by alexndrs** [comment]
Okay. Guess my only option is to change stillsource. Is their no other way?
