### ISSUE TITLE
Resolution stuck at 720p

### ISSUE THREAD

**Issue by lukasa1993** [homebridge-plugins/homebridge-camera-ffmpeg#529]
```[Camera-ffmpeg] Start streaming video from garage with 1280:-1@30fps (299kBit)```

whatever config i put this is always what i get 

this is my config…

```
{
                    "name": "garage",
                    "motion": true,
                    "videoConfig": {
                        "source": "-i rtsp://admin:passwordf@192.168.1.1/cam/realmonitor?channel=1&subtype=00",
                        "stillImageSource": "-i http://admin:password@192.168.1.1/cgi-bin/snapshot.cgi",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "preserveRatio": "W",
                        "videoFilter": "scale=1920:1080",
                        "audio": true,
                        "debug": false
                    }
                }
```

i still cant get more resolution then 720p, camera supports it… on its own ui its always 1080p

**Comment by brunokelo** [comment]
I have the same problem.

**Comment by mrmaximas** [comment]
homekit does not support resolution bigger than 720p riight now via lan and 360p via 3g/lte

**Comment by lukasa1993** [comment]
@mrmaximas homekit or homebridge ?

**Comment by mrmaximas** [comment]
homekit.

**Comment by lukasa1993** [comment]
@mrmaximas

**Comment by mrmaximas** [comment]
home app doesn’t show resolution bigger than 720p

**Comment by lukasa1993** [comment]
@mrmaximas dude i have this arlo baby and img quality is simply not comparable what this plugin shows… and camera i use in its webview shows way better quality

**Comment by mrmaximas** [comment]
> @mrmaximas dude i have this arlo baby and img quality is simply not comparable what this plugin shows… and camera i use in its webview shows way better quality

you are using home app for this "better quality" view?

**Comment by lukasa1993** [comment]
yea

**Comment by mrmaximas** [comment]
> yea

arlo baby with native homekit support. but again - homekit does not support TO VIEW on ios devices resolution bigger than 720p.
