### ISSUE TITLE
bitrate 299Kps ever

### ISSUE THREAD

**Issue by brunokelo** [homebridge-plugins/homebridge-camera-ffmpeg#530]
Hello, I'm configuring or bitrate the cameras to have better quality, but I put or parameter 4096 in the configuration file, and it is not followed it always stays at 299Kbps. according to the log below,

    "name": "KITCHEN",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp: // syno: 1614ad5c920142000818bcbd1f6f04af@192.168.0.9: 554 / Sms = 9.unicast",
                        "stillImageSource": "-i rtsp: // syno: 1614ad5c920142000818bcbd1f6f04af@192.168.0.9: 554 / Sms = 9.unicast",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 4096
[Camera-ffmpeg] Start streaming video from COZINHA with 1280:720@30fps (299kBit)

Does anyone know why?

Thank you.

**Comment by DJBenson** [comment]
I also see the bitrate always pegged at 299kbps

**Comment by MikeDProducer** [comment]
Same problem here.

**Comment by mrmaximas** [comment]
It's not a problem. it's homekit feature. 300kbps via lan/wifi, 160kbps via external 3g/lte

**Comment by MikeDProducer** [comment]
> It's not a problem. it's homekit feature. 300kbps via lan/wifi, 160kbps via external 3g/lte

Thank you. Now that you mention it, I have heard that before.
