### ISSUE TITLE
Add a switch per camera that can automate the camera feed on/off

### ISSUE THREAD

**Issue by houser42** [homebridge-plugins/homebridge-camera-ffmpeg#532]
I would like to suggest a feature for some version in the future:

* Add a switch per camera that can kill the camera feed and replace it with a generic or custom image. A simpler solution that simply makes the feed unavailable would work too, but might be confused with a camera being offline for other reasons.
That switch should then be automated by presence and such.
So for example, the obvious one, switch off all indoor cameras when someone is home.

There are a few plugins that sort of does this for specific cameras, like this one for Logitech:
https://github.com/klanchman/homebridge-logi-circle-controls

But being able to set each feed on/off by automations would probably be be really useful for may people, I would think..

Many thanks for listening.

**Comment by iRayanKhan** [comment]
What is the purpose though? Someone can still go to the cameras URL to pull up the stream, and it won't turn off the stream of the camera.

**Comment by houser42** [comment]
Hi @iRayanKhan 

Well perhaps I should have written a few words about that.
The purpose would be privacy. When people are home, the indoor cameras are not needed. 
I would like then to secure the cameras from all views via Homekit.
The direct url at least on my cameras are rudimentarily password protected so that would not be an issue. Many thanks.

**Comment by Final-Hawk** [comment]
if you are using motioneye for the streams i have some code that can do that with script 2?

**Comment by houser42** [comment]
Hi @Final-Hawk 

Appreciate the comment. Not sure if it was for me or the devs.
I probably would not know how to incorporate your code.
But maybe it is of interest to the devs for homebridge-camera-ffmpeg.
Many thanks regardless!
