### ISSUE TITLE
Ability to use button on ip doorbell?

### ISSUE THREAD

**Issue by hanzala-123** [homebridge-plugins/homebridge-camera-ffmpeg#535]
Hi, i have just setup my EZviz DB1 doorbell as an ip cam in the homebridge plugin. I was wondering if there was any way of using the physical button on the doorbell as an input to trigger the picture notification in the the home app (doorbell rang notification). This feature would be great to get around complicated ad confusing methods people have suggested. What would also be a great feature is the ability to use the motion sensor on the doorbell itself to receive the picture notification in the home app.

Kind regards, Hanzala.

**Comment by hugozheng2017** [comment]
you can use your doorbell sensor to trigger the dummy switch of the fake sensor.

**Comment by hanzala-123** [comment]
> you can use your doorbell sensor to trigger the dummy switch of the fake sensor.

How do you do that - that’s what I’m confused about.
