### ISSUE TITLE
Vcodec copy.

### ISSUE THREAD

**Issue by thevangogh** [homebridge-plugins/homebridge-camera-ffmpeg#539]
Hi all,
I have setup the plugin with vcodec copy setting, which stream the video natively if I’m connected to the local network but not via the internet. I can confirm that the internet access works if the plugin is setup with transcoding vcodec. Can anyone confirm if this is a limitation of the current design or bug? Thanks

**Comment by malhal** [comment]
I recently changed vcodec to copy but I hadn't tested viewing the camera remotely but thought I'd let you know it works fine using iPhone on iOS 13.5 over 4G and the stream is 1080p h264 supplied by Synology Surveillance Station shared stream.

Maybe your stream is too high quality for the bandwidth available?

**Comment by thevangogh** [comment]
I did a test to use 720p and 1080p on copy vcodec setting separately but encounter the same issue when viewing remotely via internet. All works fine if I use transcoding vcodec. Very odd.

**Comment by MikeDProducer** [comment]
It works correctly for me. My camera source is an Annke NVR. I am using "copy" for my codec for 5 cameras. 

This issue could have something to do with other settings for the cameras. Can you copy and paste from your config.json so we can see how the cameras are configured?

**Comment by thevangogh** [comment]
Do you mind sharing your camera video setting? e.g. resolution, frame rate, max bit rate, encoding, profile, i frame interval, video quality etc.

My config below. Thanks in advance.:
"name": "Frontyard Camera HD",
"manufacturer": “Hikvision”,
"model": “xxxI",
"serialNumber": “xxx”,
"port": 5008,
"doorbell": false,
"motion": false,
"videoConfig": 
{
"source": "-rtsp_transport tcp -i rtsp://user:password@192.168.2.4/Streaming/Channels/3",
"stillImageSource": "-i http://user:password@192.168.2.4/ISAPI/Streaming/channels/1/picture",
"vcodec": "copy",
"debug": false,
"videoFilter":"None",
"maxWidth": 3840,
"maxHeight": 2160,
"maxBitrate": 16384,
"audio": false,
"maxFPS": 25
}

**Comment by thevangogh** [comment]
when I view the camera in the Home App via local, the following is the homebridge log

frame=   60 fps= 38 q=-1.0 Lsize=    3056kB time=00:00:02.65 bitrate=9446.4kbits/s speed=1.66x                                             
video:3023kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.092780%                                        
                                                                                                                                           
Input file #0 (rtsp://user:password@192.168.2.4/Streaming/Channels/3):                                                               
  Input stream #0:0 (video): 60 packets read (3095317 bytes);                                                                              
  Total: 60 packets (3095317 bytes) demuxed                                                                                                
Output file #0 (srtp://[iphone ip]:59205?rtcpport=59205&localrtcpport=59205&pkt_size=1316):                                              
  Output stream #0:0 (video): 60 packets muxed (3095317 bytes);                                                                            
  Total: 60 packets (3095317 bytes) muxed                                                                                                  
0 frames successfully decoded, 0 decoding errors                                                                                           
[AVIOContext @ 0x557788bb6a40] Statistics: 0 seeks, 2439 writeouts          

Exiting normally, received signal 15.

**Comment by thevangogh** [comment]
When i view the camera in the Home app remotely (internet), it times out and the following is the homebridge log

frame=   60 fps= 38 q=-1.0 Lsize=    3056kB time=00:00:02.65 bitrate=9446.4kbits/s speed=1.66x                                             
video:3023kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.092780%                                        
                                                                                                                                           
Input file #0 (rtsp://user:password@192.168.2.4/Streaming/Channels/3):                                                               
  Input stream #0:0 (video): 60 packets read (3095317 bytes);                                                                              
  Total: 60 packets (3095317 bytes) demuxed                                                                                                
Output file #0 (srtp://[iphone ip]:59205?rtcpport=59205&localrtcpport=59205&pkt_size=1316):                                              
  Output stream #0:0 (video): 60 packets muxed (3095317 bytes);                                                                            
  Total: 60 packets (3095317 bytes) muxed                                                                                                  
0 frames successfully decoded, 0 decoding errors                                                                                           
[AVIOContext @ 0x557788bb6a40] Statistics: 0 seeks, 2439 writeouts          

Exiting normally, received signal 15.

**Comment by mrmaximas** [comment]
homekit does not support or use resolution more than 720p via lan and 360p via external access like 3g/lte. my advice - turn on a third stream in hikvison camera with 720p resolution and use this stream with codec = copy.

**Comment by thevangogh** [comment]
> homekit does not support or use resolution more than 720p via lan and 360p via external access like 3g/lte. my advice - turn on a third stream in hikvison camera with 720p resolution and use this stream with codec = copy.

Thanks mrmaximis. I am already using the 3rd stream with copy vcodec. 

I did further troubleshooting and found that with all the config being the same, and inter change between the copy and transcoding vcodec, the Source image would not load on the Home app as well. Maybe there’s a clue.

**Comment by damiandudycz** [comment]
Any progress with this? I have the same issue

**Comment by thevangogh** [comment]
The issue was resolved by changing settings on the camera end. 

Make sure that your video encoding is h.264 and bit rate is less than 4096. Frame rate is set to 20 frames or less. Resolution is 1080p or 720p.
