### ISSUE TITLE
Help webcam video/audio

### ISSUE THREAD

**Issue by Saku241** [homebridge-plugins/homebridge-camera-ffmpeg#540]
Hello 
I struggle to make audio work with camera-ffmpeg
When I run this command, it gaves me a file with audio working : `ffmpeg -re -ar 44100 -ac 1 -f alsa -i hw:1 -f v4l2 -c:v h264 -r 30 -s 1280x720 -itsoffset 0.5 -i /dev/video2 -copyinkf -codec:v copy -codec:a aac -ab 128k -g 10 -t 15 test.mp4`

My config is : 
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "Homebridge",
	"platforms": [{
		"platform": "Camera-ffmpeg",
		"cameras": [{
			"name": "Camera Surveillance",
			"model": "MotionEye",
			"videoConfig": {
				"source": "-re -ar 44100 -ac 1 -f alsa -i plughw:1,0 -f v4l2 -c:v h264 -i /dev/video2 -codec:v copy -ab 128k -g 10",
				"stillImageSource": "-re -f v4l2 -i /dev/video2",
				"vcodec": "copy",
				"maxStreams": 1,
				"maxWidth": 1280,
				"maxHeight": 720,
				"maxFPS": 15,
				"audio": true,
				"acodec": "aac",
				"mapvideo": "1,0",
				"mapaudio": "0,0",
				"debug": true
			}
		}]
	}]
}
```

The stream work but I dont have any sound. 

Here is the log from debug : https://pastebin.com/KTVXQ40Q 
Pasted because too long

Thanks ! Any help will be appreciated !

**Comment by Saku241** [comment]
Why did you close it ?

**Comment by donavanbecker** [comment]
check out [homebridge-camera-rpi](https://github.com/moritzmhmk/homebridge-camera-rpi).

**Comment by Saku241** [comment]
I use a USB Webcam not the raspicam

**Comment by realJustinLee** [comment]
Got the same issue here, any updates?
