### ISSUE TITLE
Ffmpeg v 2.0.0, The copy codec doesn't work correctly

### ISSUE THREAD

**Issue by sergoo-lbt** [homebridge-plugins/homebridge-camera-ffmpeg#549]
It looks like the copy codec doesn't copy the camera parameters. In the camera settings, the bitrate is set to 2048 and the homebridge log shows 299 kbit / sec. 

"name": "HikCam",
                    "manufacturer": "Hikvision",
                    "model": "HiWatch i114",
                    "serialNumber": "192.168.0.15",
                    "firmwareRevision": "1.0",
                    "videoConfig": {
                        "source": "-y -i 
![FD94F3DF-B0BB-4EBD-98AC-D3FA741968B2](https://user-images.githubusercontent.com/64399012/85177685-065fc680-b296-11ea-9879-b83473526e83.jpeg)
![592A49A5-3759-457F-8EE4-CF76445D2053](https://user-images.githubusercontent.com/64399012/85177701-0bbd1100-b296-11ea-8a6e-89d9410ffeab.png)

rtsp://admin:*******@192.168.0.15:554/unicast",
                        "stillImageSource": "-y -i rtsp://admin:*******@192.168.0.15:554/unicast",
                        "maxFPS": 25,
                        "audio": true,
                        "debug": true

**Comment by Sunoo** [comment]
I’m pretty sure the log shows what HomeKit is requesting. I haven’t seen HomeKit ever request more than 299kbps. The copy “codec” will ignore what is being requested though.

**Comment by sergoo-lbt** [comment]
> I’m pretty sure the log shows what HomeKit is requesting. I haven’t seen HomeKit ever request more than 299kbps. The copy “codec” will ignore what is being requested though.

Previously it showed the actual speed of the debug was set to true.  And the camera image quality has become noticeably worse than in the native hikconnect app.

**Comment by sergoo-lbt** [comment]
@donavanbecker , I noticed that the quality remains 299 K / bit even if you set " minBitrate”: 2048. It still remains 299 and the picture does not look nice.

**Comment by mrmaximas** [comment]
> @donavanbecker , I noticed that the quality remains 299 K / bit even if you set " minBitrate”: 2048. It still remains 299 and the picture does not look nice.

what about to use second/third hik camera stream with 720p resolution and 256-512kbps bitrate?

**Comment by sergoo-lbt** [comment]
I don't quite understand how to do this?

**Comment by mrmaximas** [comment]
sorry my friend, cheap hiwatch by hikvision caneras does not support second or third streams 🤦🏻‍♂️

**Comment by sergoo-lbt** [comment]
> sorry my friend, cheap hiwatch by hikvision cameras does not support second or third streams 🤦🏻‍♂️
Everything is OK🤝

**Comment by donavanbecker** [comment]
dupping out to #554.
