### ISSUE TITLE
iOS 13 and Photo Notifications - No Sensor/Switch Showing

### ISSUE THREAD

**Issue by jarfgames** [homebridge-plugins/homebridge-camera-ffmpeg#550]
Hello,
I tried tonight to enable iOS 13 Photo Notifications via Homebridge Config UI X. I am using a Wyze Cam 2, and the video feed works fine in HomeKit. I am using homebridge-camera-ffmpeg v2.0.0, Homebridge is v1.1.1 and node.js v12.18.1, all on a Raspberry Pi 3 using Raspbian Buster.

When I enable iOS 13 Photo Notifications, and then restart Homebridge, I do not get any new dummy sensor/switch appearing in HomeKit. For good measure, I also did a full reboot of the Raspberry Pi and still no change. 

For fun, I also tried turning the "doorbell" feature on, but that also did nothing.

For reference, here is the info from config.json (which as I mentioned I am using Homebridge Config UI X to modify):

{
            "cameras": [
                {
                    "name": "Wyze_A",
                    "manufacturer": "Wyze",
                    "model": "Wyze Cam v2",
                    "motion": true,
                    "doorbell": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://xxx:yyy@192.168.85.51/live",
                        "stillImageSource": "-rtsp_transport tcp -re -i rtsp://xxx:yyy@192.168.85.51/live",
                        "maxStreams": 2,
                        "maxFPS": 8,
                        "maxBitrate": 564,
                        "vcodec": "copy",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

Hoping someone has a suggestion/solution on how to make this work. Thanks!

**Comment by donavanbecker** [comment]
did you have camera-ffmpeg setup before you updated to 2.0.0?

**Comment by jarfgames** [comment]
> did you have camera-ffmpeg setup before you updated to 2.0.0?

Yes - I had it setup with this camera prior to the update.

**Comment by jarfgames** [comment]
And just for clarity, I never tried the iOS 13 Photo Notifications option prior to the update, so that was never turned on until now.

**Comment by jarfgames** [comment]
Inspired by your comment, I fully uninstalled the plugin and then reinstalled it. Set up the camera again from scratch and now the dummy switch/sensors appear to be showing. Thanks again.
