### ISSUE TITLE
Cameras Always Marked “Favorite” after 2.0.0

### ISSUE THREAD

**Issue by Sunoo** [homebridge-plugins/homebridge-camera-ffmpeg#551]
I don’t understand what could possibly cause this from the Homebridge and plugin side, but after updating to 2.0.0 the cameras are always marked as favorites. If you toggle that off, it has no effect and ends up on again as soon as you close the dialog.

Nothing relevant shows up in the logs, and it happens with two different Homebridge installations and from multiple iOS devices.

**Comment by MikeDProducer** [comment]
I have observed this same issue with a recent update to the Ring homebridge plugin. I wasn’t able to find a fix so I reverted to a previous version. I haven’t installed the 2.0.0 update for this camera plugin yet. I plan on doing so tomorrow. I’ll comment again if I have the same issue with this plugin.

**Comment by Sunoo** [comment]
Interestingly, I also have the Ring plugin, but that works as expected, and I’m able to have that not marked as a favorite...

**Comment by donavanbecker** [comment]
Not sure how that can be the plugin. Think it’s a HomeKit thing. Workaround that I have seen work on things like this, is diving into secondary accessories, like the motion sensor and the light switch then go back and make sure favorite is unchecked. After that close out and it should stop being a favorite.

**Comment by Sunoo** [comment]
I don’t have any secondary accessories on any of the cameras (3 cameras across 2 installations), so there is no way to do that.

And I agree it doesn’t make sense to be the plugin, but the fact remains that it worked on the previous version, so it seems to be a quirk of HomeKit being hit by some change in 2.0.0.

**Comment by mrmaximas** [comment]
simple turn-off favorite marker, than turn-on, than turn-off again, camera will be removed from favorites. it's homekit bug. I've seen the same thing with some other non-camera devices.

**Comment by Sunoo** [comment]
I was eventually able to remove them as favorites, I just kept trying periodically and eventually, one at a time, the setting took.
