### ISSUE TITLE
Wifi car dash wireless connection?

### ISSUE THREAD

**Issue by exrector** [homebridge-plugins/homebridge-camera-ffmpeg#552]
good day.  I have two cameras.  The video stream appears when connected to the camera via wifi.  please see the example and description on the link in English.  cameras only work in a mobile application.  therefore, I cannot get a stream like rtsp.  is it possible to connect such cameras to homebridge?
https://a.aliexpress.com/_dZLr01e
https://a.aliexpress.com/_dUaYFyY
Thank you in advance

**Comment by exrector** [comment]
Why did you close this question?

**Comment by donavanbecker** [comment]
> Why did you close this question?

Because it hasn’t been answered in a while and if you can’t get an rtsp stream, then it wouldn’t work with this plugin. Sorry.
