### ISSUE TITLE
Video streaming stopped working with 2.0.0

### ISSUE THREAD

**Issue by flowkeh** [homebridge-plugins/homebridge-camera-ffmpeg#553]
After updating to v2.0.0 video streaming from cameras no longer works.  Config is unchanged and snapshots are still working.  Homebridge logs do not show any errors or any requests for video streaming.  The Home app says the Camera is not responding.

I've rebooted Homebridge, rebooted the computer, turned off Firewall, uninstalled/re-installed the plug-in, removes and re-added the Homebridge bridge, and tried a clean config. 

**Homebridge Config:**

{
                    "name": "FrontYardCam",
                    "motion": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pw@192.168.0.12:554/cam/realmonitor?channel=1&subtype=2",
                        "maxStreams": 10,
                        "maxFPS": 20,
                        "minBitrate": 1536,
                        "audio": false
                    }
* **Node.js Version**: 12.18.1
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.0.0
* **Homebridge Config UI X Plugin Version**: 4.2.3
* **Operating System**: macOS 10.14.6

**Comment by donavanbecker** [comment]
did you update to `v2.0.0`?

**Comment by flowkeh** [comment]
> did you update to `v2.0.0`?

Yes this issue started after updating to v2.0.0.  It’s was working perfectly for years before updating.

**Comment by donavanbecker** [comment]
Since this changes everything over to bridged cameras, did you double check that you were viewing the bridged cameras? vs old non bridged cameras? The old non bridged cameras need to be manually removed.

**Comment by flowkeh** [comment]
> did you double check that you were viewing the bridged cameras? vs old non bridged cameras?

Yes this was with the bridged cameras after removing the original ones.  I followed the directions given in the release notes.

**Comment by AtomicLight** [comment]
> Since this changes everything over to bridged cameras, did you double check that you were viewing the bridged cameras? vs old non bridged cameras? The old non bridged cameras need to be manually removed.

Can you point to where this is documented? I don't understand and I want to learn more about what bridged vs non bridged means.

**Comment by donavanbecker** [comment]
> Can you point to where this is documented? I don't understand and I want to learn more about what bridged vs non bridged means.
> 
> 

[v2.0.0](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/releases/tag/v2.0.0)

**Comment by bjornand1** [comment]
@flowkeh Can you tell me how to downgrade to 1.3? I used the install command, but remains at 2.0, with one of my cameras not working anymore

**Comment by flowkeh** [comment]
> @flowkeh Can you tell me how to downgrade to 1.3? I used the install command, but remains at 2.0, with one of my cameras not working anymore

`npm install -g --unsafe-perm homebridge-camera-ffmpeg@v1.3.0`

My process:

- remove Homebridge from Home app (removes "new" cameras created with v2.0.0)
- run install command
- rename cameras in config
- restart Homebridge
- re-add cameras and Homebridge in Home app

**Comment by bjornand1** [comment]
@flowkeh Thanks! But I have several plugins and numerous devices running through Homebridge so I cannot rebuild this from scratch. Hope there is an update to 2.0.0 that will fix the cameras that "broke"

**Comment by flowkeh** [comment]
Just to clarify, I don't mean totally rebuilding Homebridge on the server and having to reconfigure plug-ins.  I just meant removing the virtual Homebridge "hub" from the Home app and re-adding it later.

But yeah if you have a lot of accessories that are bridged to that hub already, it would be a pain to put them all back.  

It's probably worth running a second instance of Homebridge just for the cameras and their bridge.

**Comment by bjornand1** [comment]
That might be a good idea!

**Comment by bjornand1** [comment]
Hmm, I have now set a new Homebridge instance and added the 1.3 plugin version. But even with exactly the same config parameters as I had in the original Homebridge version (when the KingCam camera worked) does not get the camera to work again. I really don't know how to solve this...

**Comment by donavanbecker** [comment]
Closing as it is a duplicate to #554.

**Comment by EddieDaYankee** [comment]
What is the command to uninstall homebridge-camera-ffmpeg on a Mac running OS 10.13.6 with the Terminal app? Thanks.
