### ISSUE TITLE
Still images do not update when using custom videoFilter in 2.x

### ISSUE THREAD

**Issue by mickgiles** [homebridge-plugins/homebridge-camera-ffmpeg#557]
**Describe The Bug:**
When using a custom videoFilter in the config, still images fail to update. The change that introduced this bug was in release 0.1.18 and was replicated in the rewrite for 2.0.
https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/blob/master/src/streamingDelegate.ts#L97
should use only the scale factor as in 
`const videoFilter = 'scale=' + resolution;`

**To Reproduce:**

Add a custom videoFilter. Mine specifically is "format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=1080 -bf 0" as I am using hardware encoding for my ffmpeg streaming

**Expected behavior:**

Still images should update in the app occasionally. Even if using a custom videoFilter

**Logs:**

```
No useful log messages exist for this issue
```

**Homebridge Config:**

```json
           "platform": "Camera-ffmpeg",
            "videoProcessor": "/custom/built/bin/ffmpeg",
            "cameras": [
                {
                    "name": "Front Porch",
                    "videoConfig": {
                        "source": "-init_hw_device vaapi=intel:/dev/dri/renderD128 -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -rtsp_transport tcp -re -i rtsp://192.168.1.11:80/cam/realmonitor?channel=1&subtype=0",
                        "stillImageSource": "-rtsp_transport tcp -re -i rtsp://192.168.1.11:80/cam/realmonitor?channel=1&subtype=0",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 1024,
                        "vcodec": "h264_vaapi",
                        "videoFilter": "format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=1080 -bf 0"
                    }
                },
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v11.6.0
* **NPM Version**: 6.13.0
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.0.0
* **Homebridge Config UI X Plugin Version**: v4.23.0
* **Operating System**: Ubuntu

**Comment by donavanbecker** [comment]
duplicate to #564
