### ISSUE TITLE
Bars in Picture

### ISSUE THREAD

**Issue by jannis2200** [homebridge-plugins/homebridge-camera-ffmpeg#558]
Hi,
in my Stream on my iPhone, there are video errors in the picture. They surely don't come from the camera stream - if I directly view the rtsp-stream, there are no errors. Is this a problem with my internet connection between iPhone and Homebridge? I have installed FFMPEG an I'm running the Homebridge in a freenas jail.

Regards,
Jannisg4g

**Comment by jannisg4g** [comment]
![Bildschirmfoto 2020-06-23 um 19 41 43](https://user-images.githubusercontent.com/40733092/85436658-aca71700-b589-11ea-94aa-cae7eea83ce4.png)

**Comment by donavanbecker** [comment]
Closing this per #554.
