### ISSUE TITLE
Update completely broke my HomeBridge

### ISSUE THREAD

**Issue by homersdonut** [homebridge-plugins/homebridge-camera-ffmpeg#559]
Hello, I updated this plugin which completely broke my Wyze cam and Ring cam streams, and also broke homebridge. when it loads with the camera-ffmpeg code in the json file it errors out saying it won't work with an old version of homebridge, and to update, but I’m running 1.1.1, subsequently the rest of my homebridge won't run unless I remove the camera-ffmpeg code.

**Comment by donavanbecker** [comment]
dup to #554
