### ISSUE TITLE
Cannot remove from favorites

### ISSUE THREAD

**Issue by faiqc** [homebridge-plugins/homebridge-camera-ffmpeg#560]
I've just installed hoobs on raspberry pi 4 (4GB RAM) and running 5 hikvision cameras in 360p of sub stream with vcodec: copy. Video is a bit laggy. Unable to remove from favourites. plz help!!!

**Comment by donavanbecker** [comment]
flip the favorite flag, then flip it on then off again. It’s a HomeKit bug.
