### ISSUE TITLE
Only able to stream outside of network

### ISSUE THREAD

**Issue by tumekee** [homebridge-plugins/homebridge-camera-ffmpeg#563]
If i am connected to 4G or internet outside of my network i can live stream just fine. If i am connected locally vai LAN or WIFI ( not that it should matter but tested both anyway ) i can get the still screenshot but not the live stream which is very odd. Im using Ubuntu server 20.04 with the firewall is turned off. Its almost like when the live stream is going via Apple TV its working , i dont know how live streams are handled locally to work out whats going on. any ideas ?

**Comment by donavanbecker** [comment]
Closing this per #554.

**Comment by tumekee** [comment]
so i worked it out after trying everything , it was because i have 2 NIC's on my server. using the "interfaceName": does nothing. disabled one of the NIC's and boom all fixed !

**Comment by Sunoo** [comment]
Interesting that interfaceName didn't do anything for you, that's exactly the scenario it's designed to help with. What value did you have it set to?
