### ISSUE TITLE
FFmpeg  Attributes Not Working

### ISSUE THREAD

**Issue by longzheng** [homebridge-plugins/homebridge-camera-ffmpeg#564]
**Describe The Bug:**
Since v2.0.0, `packetSize` seems to be removed from the `ffmpeg` command.  Not sure if intentional or not.

v2.0.0: https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/blob/ee2429e696988a931ec2738e1ed151a5f08d7d62/src/streamingDelegate.ts#L322-L323
No `this.ffmpegOpt.packetSize`

v1.3.0: https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/blob/2d07a3899059ae2c4326bc7d985de5af5d3228ae/ffmpeg.js#L391

However `README` still reference `packetSize`
https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/blame/master/README.md#L106

**Expected behavior:**
Either `packetSize` is removed from `README` or is re-added to `streamingDelegate.ts`

**Comment by donavanbecker** [comment]
can you test the latest `beta` to see if this is working now?

**Comment by longzheng** [comment]
Just looking at your PR, I can see you added this line

https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/pull/574/files#diff-018791db588d04717ecc8d17112f2c25R83

however I'm a bit confused since `this.packetSize` doesn't seem to be used anywhere.

**Comment by donavanbecker** [comment]
Would you submit a PR to beta branch?

**Comment by longzheng** [comment]
Sure, but I wasn't sure if your intention is to...
- remove support for manually specifying `packetSize` in the config?
- or, to support `packetSize` overriding the ffmpeg `pkt_size` like it did in v1.3.0?

**Comment by donavanbecker** [comment]
support `packetSize` overriding the ffmpeg `pkt_size` like it did in v1.3.0?

**Comment by donavanbecker** [comment]
> support `packetSize` overriding the ffmpeg `pkt_size` like it did in v1.3.0.

I am really just trying to maintain the plugin.

**Comment by longzheng** [comment]
Added PR #591

**Comment by donavanbecker** [comment]
> Added PR #591 

Thanks! I will get it into a beta test, and we will have people tear it!

**Comment by donavanbecker** [comment]
This can be tested in latest beta - `homebridge-camera-ffmpeg@2.0.2-beta.37`!
