### ISSUE TITLE
Unable to access rtsp stream in homebridge-camera-ffmpeg, but able to in VLC

### ISSUE THREAD

**Issue by neildawg** [homebridge-plugins/homebridge-camera-ffmpeg#584]
Hi, 

I am having trouble accessing my NVR connected camera using the config.json that is shown below. 
If I take the exact same rtsp:// address, I am able to successfully stream from the camera using VLC, so I know the address/port/path is correct. 

However, on my iOS device, I see "No Response" for Camera1 widget and when I select the widget to view the stream, I see the following error.  Unfortunately, there is no additional detailed information in the log. The "Camera1" widget in the Homebridge dashboard also shows no stream, but also has "Microphone" listed below the "Camera1" name -- not sure if this is indicative of anything. 

[7/1/2020, 12:31:15 AM] [Camera-ffmpeg] [FFMPEG] ffmpeg exited with code: 1 and signal: null (error)  

 "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Camera1",
                    "videoConfig": {
                        "source": "-re -i rtsp://<username>:<password>@10.0.1.169:10554/Streaming/Channels/101",
                        "debug": true,
                        "additionalCommandline": "-loglevel verbose"
                    }
                },
            ]
        }
    ]

Any suggestions on what I could try next to debug further ? Thanks for your help.

**Comment by neildawg** [comment]
In the above JSON, the source address is "-re -i rtsp://username:password@10.0.1.169:10554/Streaming/Channels/101". I had GT/LT around username/password which caused it to be pruned out from the text above.

**Comment by neildawg** [comment]
Reverting to 1.3.0 appears to resolve all issues and I am now able to view the stream. Also, Camera's are now labeled "Camera Control" instead of "Microphone".

**Comment by donavanbecker** [comment]
duplicate to #554
