### ISSUE TITLE
VFlip not working

### ISSUE THREAD

**Issue by metalheadz** [homebridge-plugins/homebridge-camera-ffmpeg#589]
VFlip is not working on raspberry pi zero W with official camera module V2. I've seen that a version released recently was supposed to fix this but it's not working. I tried adding the vflip command line attribute in multiples place but the snapshot and the stream ignores it. And a strange fact, despite the latest version saying that debug info is now visible in homebridge logs, the debug option is not working. Any help would be appreciated! I dont mind modifying files manually, just want to get my camera working! Thansk!

Here's my configuration file : 

"cameras": [
                {
                    "name": "piCam",
                    "uploader": false,
                    "videoConfig": {
                        "source": "-re -f video4linux2 -i /dev/video0",
                        "stillImageSource": "-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
                        "maxStreams": 4,
                        "maxFPS": 30,
                        "vcodec": "h264_omx",
                        "audio": false,
                        "vflip": true,
                        "debug": true
                    }
                }
            ],

**Environment:**

* **Node.js Version**: v12.18.1
* **NPM Version**: v6.14.5
* **Homebridge Version**: v1.1.1
* **Homebridge Camera FFmpeg Version**: v2.0.1
* **Homebridge Config UI X Plugin Version**: v4.23.2
* **Operating System**: Raspbian lite latest version with updated packages

**Comment by donavanbecker** [comment]
> And a strange fact, despite the latest version saying that debug info is now visible in homebridge logs, the debug option is not working.

Yes both debug for config and homebridge `-D` must be on. Something updating in next version

**Comment by donavanbecker** [comment]
as for `vflip` if you are willing to create a PR to fix this, I can merge it.

**Comment by metalheadz** [comment]
Yeah, I was hoping someone would point me in the right direction! Is the problem in the ffmpeg-for-homebridge package or this specific package?

**Comment by donavanbecker** [comment]
> Yeah, I was hoping someone would point me in the right direction! Is the problem in the ffmpeg-for-homebridge package or this specific package?

I believe it would be here if this was working in v1.3.0.

v2.0.0 was converting to typescript and adding bridged cameras. So could be something with the rewrite.

**Comment by donavanbecker** [comment]
duplicate to #564
