### ISSUE TITLE
Snapshot not working + manufacturer,... not updating

### ISSUE THREAD

**Issue by eliottha** [homebridge-plugins/homebridge-camera-ffmpeg#594]
Hi there,

Thanks for the amazing work on this plugin. I have my Hikvision camera set up and the stream works well apart from the lower quality. However the snapshots are not updating. The request is sent, executing the ffmpeg command manually works but in home it doesn’t update. Any idea?

Thanks,
Eliott

**Comment by eliottha** [comment]
Also, the manufacturer, model,... do not change. They stay default.
![2AABF6FA-CAE5-418B-95C6-F3AC01D19709](https://user-images.githubusercontent.com/7842156/86404969-d4e0f500-bcb0-11ea-951a-11bc02de14dc.png)

**Comment by donavanbecker** [comment]
follow issue templates..

**Comment by eliottha** [comment]
Sorry for reporting the issue, I understand you’re not investigating into this. I did not get any issue template pre-filled nor any terms when creating the issue.

**Comment by donavanbecker** [comment]
Would need more info. That’s why the template is needed.

**Comment by eliottha** [comment]
Okay. I’ll fill it when on computer again
