### ISSUE TITLE
Improve ffmpeg exit logging

### ISSUE THREAD

**Issue by isramos** [homebridge-plugins/homebridge-camera-ffmpeg#595]
I'm setting up a new camera on a new system, and I got this error message:

`[7/2/2020, 9:34:48 PM] [Camera-ffmpeg] [FFMPEG] ffmpeg exited with code: 1 and signal: null (error)` 

That is despite having debug enabled (`cameras[].videoConfig.debug: true`) . Clearly, there are not enough details to help me troubleshoot the issue.

I wish I could more easily see FFmpeg error output. Maybe include a path to a log file?

**Comment by donavanbecker** [comment]
Install beta to see if this resolves it?

`sudo npm install -g —unsafe-perm homebridge-camera-ffmpeg@beta`

**Comment by isramos** [comment]
Beta still has poor FFmpeg exit logs. That can be seen by comments in #575

**Comment by isramos** [comment]
I was doing some research and found that back in the day (2018) this library used to have complete ffmpeg logs, check out issue  #229 . Having such complete log output would help users to troubleshoot issues listed in #575
