### ISSUE TITLE
Trigger motion sensor by HTTP 

### ISSUE THREAD

**Issue by maisun** [homebridge-plugins/homebridge-camera-ffmpeg#609]
Thanks for the new possibility of using MQTT to trigger the motion sensor: https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/MQTT-Motion

I'd like to request a feature to trigger motion sensor by HTTP get request, similar to the plugin homebridge-http-webhooks
Hope it can be considered.

**Comment by donavanbecker** [comment]
@maisun if you push a pull request for this, it can be taken into consideration.

**Comment by isramos** [comment]
I like this feature. Would it use UDP or TCP?

**Comment by maisun** [comment]
> @maisun if you push a pull request for this, it can be taken into consideration.
Thx for the reply!
I wish I could but I don't have the competence unfortunately :( I ask for this feature so my camera can push motion events by sending HTTP requests. I know it can be done as I use homebridge-http-webhooks to trigger motion sensors currently.

**Comment by fennec622** [comment]
If you can request http 

try to use https://github.com/petkov/http_to_mqtt

**Comment by Sunoo** [comment]
I would agree that translating an HTTP request to MQTT would be a better approach than stuffing too much into this one plugin.

If this is a desire feature, I may write a plugin to accomplish this tomorrow, similar to [what I wrote for Dafang Hacks cameras](https://github.com/Sunoo/homebridge-dafang-mqtt-republish).

**Comment by donavanbecker** [comment]
> If you can request http
> 
> try to use https://github.com/petkov/http_to_mqtt

closing in favor of mqtt and using this example.

**Comment by Sunoo** [comment]
@maisun As I mentioned yesterday, I've written a plugin that should handle what you're looking to do: https://www.npmjs.com/package/homebridge-http-mqtt-motion

Hope this helps.
