### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by monza258** [homebridge-plugins/homebridge-camera-ffmpeg#610]
Hi everyone, 

I don’t have audio. Anyone have an idea? 

`{
                    "name": "Haustür",
                    "manufacturer": "FFMPEG",
                    "motion": true,
                    "motionTimeout": 1,
                    "doorbell": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://admin:PASSWORD@192.168.0.42:554/11",
                        "stillImageSource": "-rtsp_transport tcp -i http://admin:PASSWORD@192.168.0.42/tmpfs/auto.jpg -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 200,
                        "vcodec": "h264_omx",
                        "audio": true,
                        "packetSize": 188,
                        "hflip": true,
                        "additionalCommandline": "-x264-params intra-refresh=1:bframes=0",
                        "debug": true
                    } `

**Comment by donavanbecker** [comment]
Try turning audio off, restarting homebridge, then turn back on, then restart and see if it works then.

**Comment by monza258** [comment]
Crazy. Thank you.
