### ISSUE TITLE
Still getting error messages

### ISSUE THREAD

**Issue by thorstenman** [homebridge-plugins/homebridge-camera-ffmpeg#611]
I again tried the new plugin version, removed old cameras, checked that config.json contains no camera configs any more, deleted plugin, restarted Homebridge, installed plugin again, added my cameras (with new names), checked config.json, Homebridge did not start any more

After re-installation of plugin Homebridge does not start. Issue occurs with every v2.xx plugin version. v1.3.1 works fine.

```
Jul  6 20:52:31 HomeBridge homebridge[483]: [2020-7-6 20:52:31] Error: Missing source for camera.
Jul  6 20:52:31 HomeBridge homebridge[483]:     at new StreamingDelegate (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/streamingDelegate.ts:101:13)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at FfmpegPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/index.ts:164:31)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at FfmpegPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/index.ts:282:14)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at HomebridgeAPI.emit (events.js:327:22)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:160:14)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Module.load (internal/modules/cjs/loader.js:986:32)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Jul  6 20:52:31 HomeBridge homebridge[483]:     at internal/main/run_main_module.js:17:47
```

**Homebridge Config:**

        {
            "cameras": [
                {
                    "name": "Name 0",
                    "manufacturer": "D-link",
                    "model": "DSC-2330L",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@IP:Port/live1.sdp",
                        "audio": true,
                        "debug": false
                    }
                },
                {
                    "name": "Name 1",
                    "manufacturer": "D-link",
                    "model": "DSC-2330L",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@IP:Port/live1.sdp",
                        "audio": true,
                        "debug": false
                    }
                },
                {
                    "name": "Name 2",
                    "manufacturer": "D-link",
                    "model": "DSC-2330L",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@IP:Port/live1.sdp",
                        "audio": true,
                        "debug": false
                    }
                },
                {
                    "name": "Name 3",
                    "manufacturer": "D-link",
                    "model": "DSC-2330L",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@IP:Port/live1.sdp",
                        "audio": true,
                        "debug": false
                    }
                },
                {
                    "name": "Name 4",
                    "manufacturer": "D-link",
                    "model": "DSC-2132L",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@IP:Port/live1.sdp",
                        "audio": true,
                        "debug": false
                    }
                },
                {
                    "name": "Name 5",
                    "manufacturer": "D-link",
                    "model": "DSC-2330L",
                    "motion": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://user:password@IP:Port/live1.sdp",
                        "audio": true,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

**Screenshots:**
n/a

**Environment:**

* **Node.js Version**: 12.18.2
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.1.0
* **Homebridge Config UI X Plugin Version**: 4.23.2
* **Operating System**: Raspbian

**Comment by isramos** [comment]
It's as if the config file is not being picked up. 

If you don't get better advice, I would try resetting a few things, under Homebridge/settings:

- Unpair Bridges / Cameras / TVs / External Accessories
- Reset Homebridge Accessory 
- Remove All Cached Accessories

**Comment by california444** [comment]
I guess the old cameras are still cached. Try do delete or decouple the old cameras from the homebridge cache via Config UI X => homebrige settings and try again

**Comment by thorstenman** [comment]
Unfortunately I cannot start the UI. But I deleted the cached cameras before reinstalling. The whole Homebridge does not start anymore.

**Comment by california444** [comment]
Did you delete the old cameras in Home App or did you delete the cache in Config UI? Or both?
Before you get the error there should be also a log line with the name of the camera. Is this one of the cameras in the config file?

**Comment by thorstenman** [comment]
I deleted in Config UI.

**Comment by thorstenman** [comment]
Now I cannot even restart the Homebridge. Can just enter it via terminal.

**Comment by donavanbecker** [comment]
Do you have logs?

**Comment by thorstenman** [comment]
Which one you wanna have?

**Comment by donavanbecker** [comment]
> Unfortunately the HomeBridge is too critical for me... currently trying to restore.
> 
> 
> 
> But I can try again in the next days if you want. Which log you wanna have?

Homebridge startup log? Because didn’t you say the ui isn’t showing up?

**Comment by thorstenman** [comment]
Yeah, you are right. I'll try to find some time tomorrow and will get back to you.

Before again investing time. Was my approach correct? So:
Was on last working version for me (v1.3.1), removed old cameras via UI (not in Home App), checked that config.json contained no camera configs any more, deleted plugin, restarted Homebridge, installed plugin (newest version) again, added my cameras (with new names), checked config.json, Homebridge did not start any more

**Comment by donavanbecker** [comment]
I would of just updated and kept your config, and then clear the cache of the accessories.

**Comment by thorstenman** [comment]
OK, but cameras don't need to deleted via Apple Home App? 

An assumption I have is that the codecs might be the issue. So far I did not change the value "copy" when configuring. Is this correct?

**Comment by thorstenman** [comment]
> I would of just updated and kept your config, and then clear the cache of the accessories.

OK, but cameras don't need to deleted via Apple Home App?

An assumption I have is that the codecs might be the issue. So far I did not change the value "copy" when configuring. Is this correct?

**Comment by donavanbecker** [comment]
You will have to delete the cameras but I would wait till after you get everything up and running.

**Comment by thorstenman** [comment]
Hhm, as we want to get to the root cause - and as I do not get everything up and running... I won't delete the cameras from the  Apple Home App. Correct?

And re the further question: The cameras support h264, MJPEG, MPEG-4 and ONVIF. What value do I need to put into "Codec"? Or just leave it unchanged with value "copy".

**Comment by donavanbecker** [comment]
Closing to bring into #631, to see if it fixes your issues.

**Comment by thorstenman** [comment]
It works now. Thanks for your support!
