### ISSUE TITLE
Dafang MQTT incompatibility

### ISSUE THREAD

**Issue by Olepir** [homebridge-plugins/homebridge-camera-ffmpeg#627]
MQTT topics from a camera with [Dafang Hack](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks) not compatible with this plugin.

I need to use additional [plugin](https://github.com/Sunoo/homebridge-dafang-mqtt-republish#readme) to make it compatible.

Why is that? Is this Dafang Hack issue or homebridge-camera-ffmpeg?

Thank you

**Comment by Sunoo** [comment]
It’s just different approaches to MQTT between the Dafang and this plugin.

I think that it makes sense to keep this plugin’s MQTT somewhat generic. If it was written specifically to handle Dafang Hacks MQTT messages, all other devices would have to emulate Dafang Hacks to work with it. Alternatively, this plugin would have to somehow support a never ending list of ways that cameras send motion data.

**Comment by donavanbecker** [comment]
I agree @Sunoo, going to close this.
