### ISSUE TITLE
v2.2.0 Beta Testers Needed

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-camera-ffmpeg#631]
### Changes
  
  * Fix improper caching of MQTT timeout value.
  * Made the non-MQTT motion and doorbell switches obey the timeout value.

**Comment by Danouchka** [comment]
Hello @donavanbecker 

How do we get 2.2.0 version ?

Best, Dan

**Comment by donavanbecker** [comment]
You can test this by installing latest beta
* `sudo npm install -g --unsafe-perm homebridge-camera-ffmpeg@beta`
* To Revert `sudo npm install -g --unsafe-perm homebridge-camera-ffmpeg@latest`

**Comment by steverae68** [comment]
Happy to test - but have no idea what this MQTT is, what I need to install extra to get this working - if you can point me in the right direction, happy to configure and test this

**Comment by donavanbecker** [comment]
You don’t need to test just the MQTT.

**Comment by steverae68** [comment]
> You don’t need to test just the MQTT. 

Ok - I’ll update to this version when I get home, test and let you know - BUT I would love to understand how this MQTT would work - can it hook into the cams motion detection feed without the need for a deprecate motion detector ?

This is what I’m most interested in... I have a full HikVision setup with 3 cams so would love to get this to work without the need for a separate motion detector that triggers the cam 😁

**Comment by Sunoo** [comment]
This version has been released.
