### ISSUE TITLE
Device Info

### ISSUE THREAD

**Issue by derkaramma** [homebridge-plugins/homebridge-camera-ffmpeg#632]
I entered all of my cameras info including model, manuf., version and It does in fact save in my .json however, HomeKit isn't picking up the changes and displaying them in my home app.

fill in the customization options for each camera Ian the plug in settings.

**Expected behavior:**
should relay in the camera info on the apple home app

"name": "Living Room Cam",
                    "manufacturer": "Wyze Labs",
                    "model": "Wyze Cam v2",
                    "serialNumber": "1234567890",
                    "firmwareRevision": "4.28.4.41",

![IMG_0444](https://user-images.githubusercontent.com/45666826/87082851-7354e500-c1e0-11ea-8850-25bbc5855da9.jpeg)

**Comment by donavanbecker** [comment]
please post your config.

**Comment by Sunoo** [comment]
Did you have the manufacturer, model, etc set the first time you started Homebridge after adding your camera? Those currently don't seem to update after that point unless you remove the cached accessory.

**Comment by derkaramma** [comment]
I did not. Do I just delete and readd the accessory in home bridge??



On Jul 9, 2020, at 12:37 PM, David Maher <notifications@github.com> wrote:

﻿

Did you have the manufacturer, model, etc set the first time you started Homebridge after adding your camera? Those currently don't seem to update after that point unless you remove the cached accessory.

**Comment by Sunoo** [comment]
If you have Homebridge Config UI X, you can do it from 'Homebridge Settings' -> 'Remove Single Cached Accessory'.

**Comment by derkaramma** [comment]
Thank you so much. I feel like I scrolled past this at some point! Now I will remember lol

On Jul 9, 2020, at 12:42 PM, David Maher <notifications@github.com<mailto:notifications@github.com>> wrote:



If you have Homebridge Config UI X, you can do it from 'Homebridge Settings' -> 'Remove Single Cached Accessory'.

**Comment by Sunoo** [comment]
I'm working on removing the need for removing that cache when updating the values, but I haven't gotten it done yet.
