### ISSUE TITLE
All accessories Not Responding

### ISSUE THREAD

**Issue by SimonTurp** [homebridge-plugins/homebridge-camera-ffmpeg#640]
Hi. I upgraded to version 2.2.0 earlier today, and all my Homebridge devices (including non-camera devices) went immediately to Not Responding. If I remove the FFMPEG cameras from my config, it works as normal. If I downgrade to 2.1.1 again, it also works as normal.

Are you aware of this issue, please?

**Comment by Sunoo** [comment]
I just became aware of this shortly before this was opened, working on it now.

**Comment by SimonTurp** [comment]
Thank you! Spent like an hour trying to work it out, including reinstalling HB multiple times before realising! *doh*

**Comment by kentono** [comment]
Same here if it matters.

**Comment by App-Plant** [comment]
Just remove ffmpeg platform config from config.json and wait new update))))

**Comment by SimonTurp** [comment]
> Just remove ffmpeg platform config from config.json and wait new update))))

or, npm install -g homebridge-camera-ffmpeg@2.1.1

**Comment by Sunoo** [comment]
Okay, this is an interesting one. When I install it from the codebase on my machine, it works fine, when I install the package from NPM, everything breaks. Trying to get to the bottom of this.

**Comment by Sunoo** [comment]
Okay, should be fixed now. Sorry about that everyone. Please let me know if anyone is still having any issues on the new version.
