### ISSUE TITLE
IOS 14 Doorbell 

### ISSUE THREAD

**Issue by Skull09rus** [homebridge-plugins/homebridge-camera-ffmpeg#644]
**Describe The Bug:**
No doorbell button is displayed in HK. As an accessory in the home bridge is displayed.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

"cameras": [
                {
                    "name": "Домофон",
                    "manufacturer": "EZVIZ",
                    "doorbell": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:admin@192.168.1.113:554/h264/ch01/sub/av_stream",
                        "stillImageSource": "-re -i rtsp://admin:admin@192.168.1.113:554/h264/ch01/sub/av_stream -vframes 1 -r 1",
                        "maxFPS": 30,
                        "vcodec": "copy",
                        "audio": true,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.2
* **NPM Version**: v6.14.5
* **Homebridge Version**: try on 1.1.1 now 1.2.0-beta.29 
* **Homebridge Camera FFmpeg Version**:v2.2.1
* **Homebridge Config UI X Plugin Version**:v4.23.2
* **Operating System**:Raspbian

**Comment by Sunoo** [comment]
Please share your config.

**Comment by Skull09rus** [comment]
> Please share your config.

Add to original post

**Comment by Sunoo** [comment]
Using that config, I do see a doorbell device being created on iOS 14 beta 2. You'll need to use another app besides Apple Home to see it. I recommend [Eve](https://apps.apple.com/us/app/eve-for-homekit/id917695792) to see everything that is in HomeKit.

If you're looking for some way to trigger the doorbell, you'll probably want to enable the `switches` config option.

**Comment by Skull09rus** [comment]
> Using that config, I do see a doorbell device being created on iOS 14 beta 2. You'll need to use another app besides Apple Home to see it. I recommend [Eve](https://apps.apple.com/us/app/eve-for-homekit/id917695792) to see everything that is in HomeKit.
> 
> If you're looking for some way to trigger the doorbell, you'll probably want to enable the `switches` config option.

I'd be grateful if you could tell me how having a physical hiaomi clip to make the doorbell in ffmpeg work. I have an EVE but I can't set it up.

**Comment by Sunoo** [comment]
It's basically like this, but with doorbell instead of motion: https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/wiki/iOS-13-and-Photo-Notifications

I need to rewrite that page at some point to make it more clear.
