### ISSUE TITLE
v2.3.0 Testers Needed - HTTP Support for Motion Detect, HTTP/MQTT Support for Doorbell

### ISSUE THREAD

**Issue by Sunoo** [homebridge-plugins/homebridge-camera-ffmpeg#647]
There is now HTTP motion and doorbell support, valid commands:
 * Trigger Motion: `http://hostname:port/motion?Camera%20Name`
 * Reset Motion: `http://hostname:port/motion/reset?Camera%20Name`
 * Trigger Doorbell: `http://hostname:port/doorbell?Camera%20Name`

To enable HTTP support, set the port you want the server to run on in the `porthttp` config option.

For MQTT, the doorbell has been moved to a new topic, because of this, the default MQTT topic in the config has changed from `homebridge/motion` to just `homebridge`. To compensate for this, and because the previous version didn't properly read that config option, if you have `homebridge/motion` configured, `homebridge` will be used instead.

 * Trigger Motion: topic `homebridge/motion` with message `Camera Name` (same as previous versions)
 * Reset Motion: topic `homebridge/motion/reset` with message `Camera Name` (same as previous versions)
 * Trigger Doorbell: topic `homebridge/doorbell` with message `Camera Name`

I'll be updating the wiki with clearer directions later.

**Comment by App-Plant** [comment]
MQTT topic homebridge/doorbell works perfect. Thx for support.
homebridge-camera-ffmpeg v2.2.2-beta.6

**Comment by Sunoo** [comment]
If nobody finds any issues with this build, I plan to release it tomorrow or Wednesday.

**Comment by flipit** [comment]
http works perfectly for me.  Thx for taking this on.

**Comment by Sunoo** [comment]
Version 2.3.0 has been released.

**Comment by ctrl-data** [comment]
Http doesn't seem to be working, I believe it's because I'm not setting it up properly however the documentation seems confusing to me. What port is supposed to be used when sending the http request, the port of the homebridge server, camera stream, or something else entirely. Thank you for your time.

**Comment by ctrl-data** [comment]
The wiki post showing how to set this up should bring more light to the portHttp flag in the config. It isn't mentioned and is only shown in the config example.

**Comment by Sunoo** [comment]
@ctrl-data That’s the problem with writing documentation when I know how things work already, I leave important details out.

I’ll get that updated some time this morning.

**Comment by ctrl-data** [comment]
@Sunoo Thankyou, took me some time to figure out why it wasn't working the first time. While I have you (if I do) do you have experience in MotionEye? I'm trying to send the webhook and no matter what I do it doesn't work, but when I send it via terminal identically (I'm using curl in Send Command) it works. But when I try on MotionEye nothing happens. I know it's detecting motion because I can see the tracking boxes but I've had no luck all night.

**Comment by Sunoo** [comment]
@ctrl-data I'm not familiar with MotionEye, sorry. I tried to take a quick look, and it looks like they're based on POST instead of GET, but I the code I wrote for HTTP support should allow for that. I really can't find any meaningful documentation on the feature though. If you know of any, let me know and I'll take a look.

It does look like there is the option to run a command instead of a webhook, so you could potentially set it up to use curl instead? I'm flying pretty blind on this one though, due to lack of information on MotionEye.

**Comment by ctrl-data** [comment]
@Sunoo Hello, thanks for your input. I ended up figuring it out. Using plain webhooks in the interface or even running a curl command didn't seem to work. 

However creating a simple script with the curl command inside it and then executing that script seemed to fix the issue.
i.e.

`curl http://hostname:port/motion?Camera%20Name` and then `/home/%name%/motionOn.sh` in the Execute Command section.

I'll post to the MotionEye team to find a fix in the future. In the meantime it's something to keep in mind until it is fixed for those having issues integrating HTTP support with MotionEye.

**Comment by Sunoo** [comment]
@ctrl-data Glad you got it going. And I agree, that does sound like an issue on MotionEye's side.
