### ISSUE TITLE
Add username / password for MQTT broker

### ISSUE THREAD

**Issue by mishakim** [homebridge-plugins/homebridge-camera-ffmpeg#655]
**Is your feature request related to a problem? Please describe:**
My MQTT broker has a username and password. Without having a config for that in the plugin, can't use MQTT for doorbell or motion

**Describe the solution you'd like:**
add MQTT Broker username and password to config

**Describe alternatives you've considered:**
Using HTTP for now, but would rather use MQTT

**Additional context:**
FWIW, my MQTT broker is internal to NodeRed, and my doorbell is an ESP8266 that sends an MQTT message. For now NodeRed is receiving the message and resending it by HTTP, but with this fix, could have it go directly from sensor to homebridge

**Comment by Sunoo** [comment]
Easy enough. I’ll get that added to the beta version shortly, and it’ll be in the next release.

**Comment by Sunoo** [comment]
Okay, added to the latest beta, you can install it with `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. I did some quick testing, but please let me know if this works for you.

**Comment by mishakim** [comment]
Worked perfectly, thanks!

**Comment by Sunoo** [comment]
Glad it's working for you, I'll close this out now and it'll be in the next release (but feel free to stick on the beta until then).
