### ISSUE TITLE
minBitrate seems to not work

### ISSUE THREAD

**Issue by agneevX** [homebridge-plugins/homebridge-camera-ffmpeg#657]
**Describe The Bug:**

The stream seems to default to 299 Kbit/s regardless of what's set in `minBitrate`.

This issue has cropped up in the last few versions of this plugin. 

**To Reproduce:**
Set `minBitrate` and restart HB. 

**Expected behavior:**
The video stream should be in the minimum quality as configured. 

**Logs:**

```text
[7/15/2020, 7:49:20 PM] [Camera ffmpeg] Starting Front Gate CCTV video stream (1280x720, 20 fps, 299 kbps, 1316 mtu)...
```

**Homebridge Config:**

```json
{
                    "name": "Front Gate CCTV",
                    "manufacturer": "D-Link",
                    "model": "DCS-933L",
                    "firmwareRevision": "1.15.01",
                    "motion": false,
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://admin:password@10.0.0.6/mjpeg.cgi",
                        "stillImageSource": "-f mjpeg -i http://admin:password@10.0.0.6/image.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "minBitrate": 7500,
                        "maxBitrate": 7501,
                        "videoFilter": "scale=640:480",
                        "vcodec": "libx264",
                        "audio": false,
                        "debug": false
                    }
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.18.2
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.3.0
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: Raspberry Pi OS Buster

**Comment by sergoo-lbt** [comment]
> **Describe The Bug:**
> 
> The stream seems to default to 299 Kbit/s regardless of what's set in `minBitrate`.
> 
> This issue has cropped up in the last few versions of this plugin.
> 
> **To Reproduce:**
> Set `minBitrate` and restart HB.
> 
> **Expected behavior:**
> The video stream should be in the minimum quality as configured.
> 
> **Logs:**
> 
> ```
> [7/15/2020, 7:49:20 PM] [Camera ffmpeg] Starting Front Gate CCTV video stream (1280x720, 20 fps, 299 kbps, 1316 mtu)...
> ```
> 
> **Homebridge Config:**
> 
> ```json
> {
>                     "name": "Front Gate CCTV",
>                     "manufacturer": "D-Link",
>                     "model": "DCS-933L",
>                     "firmwareRevision": "1.15.01",
>                     "motion": false,
>                     "videoConfig": {
>                         "source": "-re -f mjpeg -i http://admin:password@10.0.0.6/mjpeg.cgi",
>                         "stillImageSource": "-f mjpeg -i http://admin:password@10.0.0.6/image.jpg",
>                         "maxStreams": 2,
>                         "maxWidth": 1280,
>                         "maxHeight": 720,
>                         "maxFPS": 20,
>                         "minBitrate": 7500,
>                         "maxBitrate": 7501,
>                         "videoFilter": "scale=640:480",
>                         "vcodec": "libx264",
>                         "audio": false,
>                         "debug": false
>                     }
> ```
> 
> **Screenshots:**
> 
> **Environment:**
> 
> * **Node.js Version**: 12.18.2
> * **NPM Version**: 6.14.5
> * **Homebridge Version**: 1.1.1
> * **Homebridge Camera FFmpeg Version**: 2.3.0
> * **Homebridge Config UI X Plugin Version**:
> * **Operating System**: Raspberry Pi OS Buster

Confirm. It hasn't been working for a long time.

**Comment by Sunoo** [comment]
I'm looking into this.

**Comment by Sunoo** [comment]
Okay, I’ve pushed a new beta which should fix this, you can install it with `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. Please test and let me know if the problem is resolved for you.

**Comment by MikeDProducer** [comment]
This is how HomeKit works. There isn't a way around it as far as I know. It has always just streamed to your iPhone around 300.

**Comment by Sunoo** [comment]
@MikeDProducer There was a minBitrate setting in this plugin in the past, but it seemed like it got removed around the 2.0.0 release, probably by accident. I've restored that option in the beta I pushed this morning.

That setting basically overrides what the iOS device is asking for and sends higher bitrate video. In my experience, the Home app is perfectly happy dealing with this, though I do not use the setting myself.

**Comment by sergoo-lbt** [comment]
> Okay, I’ve pushed a new beta which should fix this, you can install it with `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. Please test and let me know if the problem is resolved for you.

My friend! Thank you for returning this parameter! Everything works on the latest beta! Here is only for etil that by default in the plugin is the codec copy, right? He's fine. However, if you forcibly select the copy codec in the menu, the stream stops working. Sorry if I'm not clear, I'm writing through a translator because I don't know English well)))
![88C3BFBE-B87A-4537-B2BA-08272550EC60](https://user-images.githubusercontent.com/64399012/87587976-56e30c00-c6fc-11ea-8ce3-76d23277708c.jpeg)

**Comment by Sunoo** [comment]
@sergoo-lbt I'm not sure I understand. Are you saying copy works, or that copy doesn't work?

During my testing, I tried with both a camera configured as copy and one using mjpeg.

**Comment by sergoo-lbt** [comment]
> I'm not sure I understand. Are you saying copy works, or that copy doesn't work?
> 
> During my testing, I tried with both a camera configured as copy and one using mjpeg.

Works if you delete the value in the codec settings bar. Leaving it as the default. If you choose from the suggested options of codecs copy, so that it is registered in the config, then it does not work.

**Comment by Sunoo** [comment]
Okay, I think I understand what you're saying. In the code though, 'libx264' is the default codec, despite what the Config UI says.
