### ISSUE TITLE
No Video stream from my camera

### ISSUE THREAD

**Issue by drheck** [homebridge-plugins/homebridge-camera-ffmpeg#664]
**Describe Your Problem:**

What do i wrong? In iSpy&VLC the connection works and i see the video of my camera. But not in HomeKit.
Errors: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
Thank you very much.
Peter

**Logs:**

```
Show the Homebridge logs here.
Remove any sensative information.
```
Jul 16 20:56:01 hbridge3 homebridge[478]: [2020-7-16 20:56:01] [Camera-ffmpeg] Snapshot from Kamera Terrasse at 480:270
Jul 16 20:56:01 hbridge3 homebridge[478]: [2020-7-16 20:56:01] [Camera-ffmpeg] Kamera Terrasse snapshot command: ffmpeg rtsp_transport tcp -i rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp -frames:v 1 -vf scale=480:270 -f image2 -
Jul 16 20:56:12 hbridge3 homebridge[478]: [2020-7-16 20:56:12] [Camera-ffmpeg] Snapshot from Kamera Terrasse at 480:270
Jul 16 20:56:12 hbridge3 homebridge[478]: [2020-7-16 20:56:12] [Camera-ffmpeg] Kamera Terrasse snapshot command: ffmpeg rtsp_transport tcp -i rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp -frames:v 1 -vf scale=480:270 -f image2 -
Jul 16 20:56:15 hbridge3 homebridge[478]: [2020-7-16 20:56:15] [Camera-ffmpeg] Starting Kamera Terrasse video stream (1280x720, 30 fps, 299 kbps, 1316 mtu)... debug enabled
Jul 16 20:56:15 hbridge3 homebridge[478]: [2020-7-16 20:56:15] [Camera-ffmpeg] Kamera Terrasse command: ffmpeg rtsp_transport tcp -i rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 8988225 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params xrFIzCAfmvkOQ0h9keENi1GGHKQBgDVDmTt9nWW4 srtp://192.168.113.93:49244?rtcpport=49244&localrtcpport=49244&pkt_size=1316 -loglevel level+verbose
Jul 16 20:56:15 hbridge3 homebridge[478]: [2020-7-16 20:56:15] [Camera-ffmpeg] Kamera Terrasse: [info] ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
Jul 16 20:56:15 hbridge3 homebridge[478]: [2020-7-16 20:56:15] [Camera-ffmpeg] Kamera Terrasse: [info]   libavutil      56. 31.100 / 56. 31.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libavcodec     58. 54.100 / 58. 54.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libavformat    58. 29.100 / 58. 29.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libavdevice    58.  8.100 / 58.  8.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libavfilter     7. 57.100 /  7. 57.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libswscale      5.  5.100 /  5.  5.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libswresample   3.  5.100 /  3.  5.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [info]   libpostproc    55.  5.100 / 55.  5.100
Jul 16 20:56:15 hbridge3 homebridge[478]: [2020-7-16 20:56:15] [Camera-ffmpeg] Kamera Terrasse: [tcp @ 0x2ff7610] [verbose] Starting connection attempt to 192.168.XXX.XX port 554
Jul 16 20:56:15 hbridge3 homebridge[478]: [2020-7-16 20:56:15] [Camera-ffmpeg] Kamera Terrasse: [tcp @ 0x2ff7610] [verbose] Successfully connected to 192.168.XXX.XX port 554
Jul 16 20:56:16 hbridge3 homebridge[478]: [2020-7-16 20:56:16] [Camera-ffmpeg] Kamera Terrasse: [error] rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
Jul 16 20:56:16 hbridge3 homebridge[478]: [2020-7-16 20:56:16] [Camera-ffmpeg] [Kamera Terrasse] ffmpeg exited with code: 1 and signal: null (Error)
Jul 16 20:56:16 hbridge3 homebridge[478]: [2020-7-16 20:56:16] [Camera-ffmpeg] Stopped Kamera Terrasse video stream!
Jul 16 20:56:34 hbridge3 homebridge[478]: [2020-7-16 20:56:34] [Camera-ffmpeg] Snapshot from Kamera Terrasse at 480:270
Jul 16 20:56:34 hbridge3 homebridge[478]: [2020-7-16 20:56:34] [Camera-ffmpeg] Kamera Terrasse snapshot command: ffmpeg rtsp_transport tcp -i rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp -frames:v 1 -vf scale=480:270 -f image2 -
Jul 16 20:56:35 hbridge3 homebridge[478]: [2020-7-16 20:56:35] [Broadlink RM] Terrasse On/Off getSwitchState: true
Jul 16 20:56:45 hbridge3 homebridge[478]: [2020-7-16 20:56:45] [Camera-ffmpeg] Snapshot from Kamera Terrasse at 480:270
Jul 16 20:56:45 hbridge3 homebridge[478]: [2020-7-16 20:56:45] [Camera-ffmpeg] Kamera Terrasse snapshot command: ffmpeg rtsp_transport tcp -i rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp -frames:v 1 -vf scale=480:270 -f image2 -
Jul 16 20:57:05 hbridge3 homebridge[478]: [2020-7-16 20:57:05] [Camera-ffmpeg] Snapshot from Kamera Terrasse at 480:270
Jul 16 20:57:05 hbridge3 homebridge[478]: [2020-7-16 20:57:05] [Camera-ffmpeg] Kamera Terrasse snapshot command: ffmpeg rtsp_transport tcp -i rtsp://admin:XXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp -frames:v 1 -vf scale=480:270 -f image2 -

**Homebridge Config:**

```json
Show your homebridge config.json here. 
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```
        {
            "mqtt": "192.168.XXX.XX",
            "cameras": [
                {
                    "name": "Kamera Terrasse",
                    "manufacturer": "Hikam",
                    "model": "A72",
                    "motion": false,
                    "videoConfig": {
                        "source": "rtsp_transport tcp -i rtsp://admin:XXXXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge Camera FFmpeg Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by Sunoo** [comment]
The only obvious thing I’m seeing is you missed a - before rtsp_transport, can you try fixing that and see if it resolves your issue?

```
        {
            "mqtt": "192.168.XXX.XX",
            "cameras": [
                {
                    "name": "Kamera Terrasse",
                    "manufacturer": "Hikam",
                    "model": "A72",
                    "motion": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://admin:XXXXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Comment by drheck** [comment]
Thank you for your fast answer.
But where must be the a ?
Thanks,
Peter
[cid:image001.png@01D65BBE.2CE30E40]

Mit freundlichen Grüßen
   Dr.-Ing. Peter Heck
________________________________
Dr.-Ing. Peter Heck
Beethovenstraße 5
67685 Weilerbach
Telefon: +49 6374 993322
Mobiltelefon: +49 172 6124786


Von: David Maher <notifications@github.com>
Gesendet: Donnerstag, 16. Juli 2020 21:45
An: homebridge-plugins/homebridge-camera-ffmpeg <homebridge-camera-ffmpeg@noreply.github.com>
Cc: drheck <drheck@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [homebridge-plugins/homebridge-camera-ffmpeg] No Video stream from my camera (#664)


The only obvious thing I’m seeing is you missed a - before rtsp_transport, can you try fixing that and see if it resolves your issue?

        {



            "mqtt": "192.168.XXX.XX",



            "cameras": [



                {



                    "name": "Kamera Terrasse",



                    "manufacturer": "Hikam",



                    "model": "A72",



                    "motion": false,



                    "videoConfig": {



                        "source": "-rtsp_transport tcp -i rtsp://admin:XXXXXXX@192.168.XXX.XX:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp",



                        "maxStreams": 2,



                        "maxWidth": 1280,



                        "maxHeight": 720,



                        "maxFPS": 30,



                        "audio": false,



                        "debug": true



                    }



                }



            ],



            "platform": "Camera-ffmpeg"



        }

**Comment by Sunoo** [comment]
I posted a corrected version of your config in my last comment.

**Comment by drheck** [comment]
Ups. Sorry you meant the -
Now it works, but on the iphone I see now that the camera show a live stream.
I think that is not good for the consumption.

What must I configure for the stillimagesourc?
"stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",

Thank you very mutch 😊

Mit freundlichen Grüßen
   Dr.-Ing. Peter Heck
________________________________
Dr.-Ing. Peter Heck
Beethovenstraße 5
67685 Weilerbach
Telefon: +49 6374 993322
Mobiltelefon: +49 172 6124786


Von: David Maher <notifications@github.com>
Gesendet: Donnerstag, 16. Juli 2020 22:14
An: homebridge-plugins/homebridge-camera-ffmpeg <homebridge-camera-ffmpeg@noreply.github.com>
Cc: drheck <drheck@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [homebridge-plugins/homebridge-camera-ffmpeg] No Video stream from my camera (#664)


I posted a corrected version of your config in my last comment.

**Comment by Sunoo** [comment]
If your camera doesn’t provide a still image (and many don’t), you can just leave that blank, and the plugin should handle it for you.

**Comment by drheck** [comment]
Okay. Thanks a lot.
You can close the issue.

Mit freundlichen Grüßen
   Dr.-Ing. Peter Heck
________________________________
Dr.-Ing. Peter Heck
Beethovenstraße 5
67685 Weilerbach
Telefon: +49 6374 993322
Mobiltelefon: +49 172 6124786


Von: David Maher <notifications@github.com>
Gesendet: Donnerstag, 16. Juli 2020 22:29
An: homebridge-plugins/homebridge-camera-ffmpeg <homebridge-camera-ffmpeg@noreply.github.com>
Cc: drheck <drheck@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [homebridge-plugins/homebridge-camera-ffmpeg] No Video stream from my camera (#664)


If your camera doesn’t provide a still image (and many don’t), you can just leave that blank, and the plugin should handle it for you.

**Comment by Sunoo** [comment]
Great, glad things are working for you now.
